### ISSUE TITLE
Plugin server known issues/missing functionality superlist

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#10421]
This is a priority queue of impactful changes to the plugin server we should tackle regarding issues and key missing functionality:

- [x] CH <> Postgres out of sync (should be lower than 1%, unless we also move the goal post) https://metrics.posthog.com/d/RZzZ-Mj7z/person-data-integrity?orgId=1  
https://github.com/orgs/PostHog/projects/50/
- [x] Person deletion in Django is faulty: https://github.com/PostHog/posthog/issues/10236
- [x] Dependabot alerts
- [ ] https://github.com/PostHog/charts-clickhouse/pull/243
- [ ] Exposing person to plugins https://github.com/PostHog/posthog/issues/10192
- [x] Plugins activity log
- [ ] Retries for person updates https://github.com/PostHog/posthog/issues/10396

- [x] Fixing issues in slow query list: https://metabase.posthog.net/question/344-most-time-consuming-postgres-queries
