### ISSUE TITLE
CSV Exporting should be finished

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#10607]
## Is your feature request related to a problem?

Yes, CSV exporting of thing is mostly there (behind a feature flag). To release this we still have a few things todo...

## Describe the solution you'd like
**TODO**
- [x] Add back in the Object storage work ~~so we aren't loading everything into memory~~
- [x] Agree on MAX and PAGE limits 
- [x] Update UI where appropriate to indicate the new limits
- [x] Add tests to cover each response type (e.g. Insights, Persons)
- [ ] Support Dashboard CSV?
- [x] Support Person Modal Export

## Describe alternatives you've considered

Leaving it broken 😊 

### Export Insight to CSV

data for the insight as per current filters

<img width="692" alt="Screenshot 2022-07-01 at 15 32 11" src="https://user-images.githubusercontent.com/984817/176914714-c1687187-6688-4004-9600-039ac452134b.png">

### Export to Dashboard

It's "just" exporting each insight on the dashboard to CSV using the combined filters

### Live Events

export a limited number of events matching current filters/columns

currently ignores page filters and fails trying to read a year of data in order to limit it

[[https://app.posthog.com/api/projects/2/events.csv?properties=[]&orderBy=["-timestamp"]&after=2021-06-27T09%3A45%3A24.882Z](https://app.posthog.com/api/projects/2/events.csv?properties=%5B%5D&orderBy=%5B%22-timestamp%22%5D&after=2021-06-27T09%3A45%3A24.882Z)](https://app.posthog.com/api/projects/2/events.csv?properties=%5B%5D&orderBy=%5B%22-timestamp%22%5D&after=2021-06-27T09%3A45%3A24.882Z)

### Persons & Groups

Currently 10,000 persons (not groups)

<img width="698" alt="Screenshot 2022-07-01 at 15 32 17" src="https://user-images.githubusercontent.com/984817/176914738-1427e826-08d3-4066-ba22-941207bc6779.png">

(Note nice addition of what is going to be exported)

[https://app.posthog.com/api/person/.csv?properties=[{"key"%3A"%24geoip_continent_name"%2C"value"%3A["Europe"]%2C"operator"%3A"exact"%2C"type"%3A"person"}]](https://app.posthog.com/api/person/.csv?properties=%5B%7B%22key%22%3A%22%24geoip_continent_name%22%2C%22value%22%3A%5B%22Europe%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D)

### Cohorts

export users in a cohort

opens a window with URL [https://app.posthog.com/api/person.csv?cohort=10156](https://app.posthog.com/api/person.csv?cohort=10156)

doesn’t work

# Out of Scope

* Recordings
* Feature Flags
* Experiments
* property definitions
* event definitions

**Comment by pauldambra** [comment]
We agreed to reduce live event limit to 3,500. It was previously but still said 10,000 in the UI

**Comment by pauldambra** [comment]
Persons modal is currently disabled for all users. #10824 updates it to work with the new mechanism (regardless of whether we turn it back on)

**Comment by pauldambra** [comment]
CSV and Image exports now write to object storage.

We don't try to avoid holding the whole export in RAM
