### ISSUE TITLE
Team east Sprint 1.39-2 bug bash

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#11344]
I had a look through the issues that just @joethreepwood and @corywatilo have posted, and found a lot of things we need to work on. Here's a loosely categorised list of bugs, mostly frontend, with 95% issues from from Joe and Cory. (Edit: and Chris)

Legend:
🐞 - bug with cause to investigate
⌨️ - ready to bash
🎨 - needs product design input
🏃 - in progress
🍩 - juicy feature
☠️ - has been attempted
🍯 - ooh, yummy
🐲 - here be dragons

Insights
- [ ] 🎨 🍩 https://github.com/PostHog/posthog/issues/10211 - show filters in view mode
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10265 - better empty/unreachable state
- [x] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/9570 https://github.com/PostHog/posthog/issues/9568 https://github.com/PostHog/posthog/issues/10023 - sort filter on breakdown broken <- @pauldambra #11456 
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10678 - prepopulate list with existing tags
- [x] 🐞 https://github.com/PostHog/posthog/issues/5916 - compare previous doesn't reset @pauldambra 
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/7840 - graphs go too far back

Filters
- [x] 🏃 🍩 https://github.com/PostHog/posthog/issues/8257 - get rid of always loaded property definitions <-- #11454 #11463 #11467 @mariusandra
- [ ] 🐞 🍩 https://github.com/PostHog/posthog/issues/10408 - last seen / first seen not showing 
- [ ] 🐞 https://github.com/PostHog/posthog/issues/11181 - last modified also not showing
- [ ] 🐞 🍩 https://github.com/PostHog/posthog/issues/11293 - taxonomic filter opens weird on small screens
- [ ] 🐞 https://github.com/PostHog/posthog/issues/8564 - does not show property value select for multiple options
- [ ] 🏃 https://github.com/PostHog/posthog/issues/11140 - button to duplicate OR filter (community contributor)
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/9667 - add first filter with one click
- [x] ⌨️ https://github.com/PostHog/posthog/issues/9666 - add "..." better to large properties in select
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/9664 - date filter custom range broken
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10727 - "date to now" option for filter
- [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/11142 - add property filters to cohorts, without bad workarounds
- [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/10798 - trailing slashes in url filters
- [ ] ⌨️ 🍩 🐲 https://github.com/PostHog/posthog/issues/7970 - filters close in a wonky way

Funnels
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10144 - funnel creation dorky
- [ ] 🐞 https://github.com/PostHog/posthog/issues/10284 https://github.com/PostHog/posthog/issues/11349 - funnel breakdown acting weird
- [ ] 🐞 https://github.com/PostHog/posthog/issues/10226 - no relative values on left-to-right funnels
- [ ] 🎨 https://github.com/PostHog/posthog/issues/9115 - add funnel step is odd
- [ ] 🐞 https://github.com/PostHog/posthog/issues/8517 - funnel bug.. is it still open?

Persons
- [ ] 🍩 🐞 https://github.com/PostHog/posthog/issues/11466 @benjackwhite 
  - [ ] 🐞 https://github.com/PostHog/posthog/issues/9565 - persons not loading @benjackwhite 
  - [ ] 🍩 https://github.com/PostHog/posthog/issues/11352 - persons modal doesn't show all persons @benjackwhite 
  - [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/11480 - updated persons modal to fix layout regressions @benjackwhite 

Settings
- [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/10229 - separate toolbar and recording URLs

Visualizations
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/11276 - % of total area
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/9662 - tooltips look squished
- [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/9663 - better labels for months, or only select full months?
- [ ] 🎨 https://github.com/PostHog/posthog/issues/4154 - change date format
- [ ] 🐞 https://github.com/PostHog/posthog/issues/7468 - lifecycle report is weird

Visualizations - can these be linked better?
- [ ] 🎨 https://github.com/PostHog/posthog/issues/11427
- [ ] 🎨 https://github.com/PostHog/posthog/issues/11433
- [ ] 🎨 Custom time legends (see [artboard](https://www.figma.com/file/HwUmk7WqccLkGgNNGAs4zN/Art-board?node-id=4934%3A29109))

Tables technical improvements
- [x] ⌨️ https://github.com/PostHog/posthog/issues/10813 - wrapping the table for feature flags - @pauldambra 
- [ ] ⌨️ 🍩 ☠️ 🍯 https://github.com/PostHog/posthog/issues/9567 - sticky first column
- [ ] ⌨️ 🍩 ☠️ 🍯 https://github.com/PostHog/posthog/issues/9566 - horizontal scrolling

Tables UX issues
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10228 - cohorts table alignment
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/11146 - last total sum column has a bad button for sort
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/8408 - more problems with that column
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10595 - user properties table looks bad
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10227 - make experiments table sortable

Other UX issues
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10275 - modal weird in correlation analysis 
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/9520 - register and signin placement
- [ ] 🎨 https://github.com/PostHog/posthog/issues/4885 - too many login requests breaks frontend (no nice error)
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/11475

Dashboards
- [ ] 🍩 https://github.com/PostHog/posthog/issues/8460 - edit time for one insight on a dashboard
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10264 - funnel conversion rate in card
- [ ] 🐞 https://github.com/PostHog/posthog/issues/10263 - tiles don't update if you edit insight descriptions
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10262 - improve "add first insight" CTA
- [ ] ⌨️ 🍩 https://github.com/PostHog/posthog/issues/9241 - dashboard descriptions extend too far
- [x] ⌨️ https://github.com/PostHog/posthog/issues/9239 - wrong icon + button with no permission to click it <- #11457 @pauldambra 
- [ ] 🐲 https://github.com/PostHog/posthog/issues/10759 - multi dashboard caching

Annotations
- [ ] ☠️ 🍩 🍯 🐲 https://github.com/PostHog/posthog/issues/9511 - annotations are off
- [ ] ☠️ 🍩 🍯 https://github.com/PostHog/posthog/issues/11136 - annotations
- [ ] ☠️ 🍩 https://github.com/PostHog/posthog/issues/7841 - same
- [ ] ☠️ https://github.com/PostHog/posthog/issues/9058 - bad UX
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/8568 - too narrow
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/11453 - first point in time can't show existing annotations

Actions & data management
- [ ] 🐞 https://github.com/PostHog/posthog/issues/11076 - data quality issues with actions
- [ ] 🐞 https://github.com/PostHog/posthog/issues/10783 - actions don't refresh in the app on edit
- [ ] 🐞 🍩 https://github.com/PostHog/posthog/issues/4506 - modified actions won't refresh charts used by them
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10723 - show more metadata
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10677 - not clear if we click on save or not
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10260 - create new action toolbar modal design broken
- [ ] 🐞 https://github.com/PostHog/posthog/issues/4507 - weird field dynamics
- [ ] 🎨 https://github.com/PostHog/posthog/issues/4505 - verify that actions match events without saving
- [ ] 🎨 https://github.com/PostHog/posthog/issues/4503 - can't remove fields from actions
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10218 - bad blank text

CSV
- [ ] 🎨 https://github.com/PostHog/posthog/issues/9086 - choose columns to export
- [ ] 🍩 https://github.com/PostHog/posthog/issues/9084 - item count on CSVs
- [ ] 🍩 https://github.com/PostHog/posthog/issues/10410 - how many people are in a list?

Toolbar
- [ ] 🎨 https://github.com/PostHog/posthog/issues/11138 - add as match group to existing action
- [x] ⌨️ https://github.com/PostHog/posthog/issues/4497 - toolbar goes behind scrollbar
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10846 - broken toast
- [ ] 🐞 🐲 https://github.com/PostHog/posthog/issues/10796 - can't save something
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10679 - add tags and descriptions to actions
- [ ] 🐞 https://github.com/PostHog/posthog/issues/9286 - something breaks
- [x] ⌨️ https://github.com/PostHog/posthog/issues/6420 - follows me around - @pauldambra 

Forms & accessibility
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10335 - use label elements

Web performance
- [ ] 🏃 https://github.com/PostHog/posthog/issues/11337 - Icon position regression

Apps
- [ ] 🎨 https://github.com/PostHog/posthog/issues/10181 - sync app libraries on app and posthog.com
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/9838 - req: mailchimp connector app
- [x] 🎨 https://github.com/PostHog/posthog/issues/7012 - pubsub plugin icon - @pauldambra 

Billing
- [ ] 🎨 https://github.com/PostHog/posthog/issues/9886 - billing prompt. fixed?
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/10862 - renaming billing plans in app

Session Recordings
- [ ] 🐞 https://github.com/PostHog/posthog/issues/9647 - custom fonts in session recordings?

Data quality
- [ ] ⌨️ https://github.com/PostHog/posthog/issues/7795 - non-mobile devices are "none"

Out of scope new features
- 🇳🇿 https://github.com/PostHog/posthog/issues/9784 - re-engagement emails for onboarding
- 🇳🇿 https://github.com/PostHog/posthog/issues/9509 - link to areas of product
- 🇳🇿 https://github.com/PostHog/posthog/issues/7875 - correlation analysis for cohorts
- 🇳🇿 https://github.com/PostHog/posthog/issues/10320 - add comments on saved insights
- 🇳🇿 https://github.com/PostHog/posthog/issues/3150 - productize in-person announcements
- 🇳🇿 https://github.com/PostHog/posthog/issues/9061 - animate sidebar icons
- 🏃 https://github.com/PostHog/posthog/issues/10193 - demo environment tutorial walkthough

Needs thought
- ❓ https://github.com/PostHog/posthog/issues/10322 - tag plugins with known issues
- ❓ https://github.com/PostHog/posthog/issues/6406 - expose hotkeys somewhere

I believe we have some work to do 😅. The next step is to Eisenhower the list above, and figure out the urgent/important split

**Comment by neilkakkar** [comment]
re: The FF enabled/disabled task: We're going to take that on next week for our FF UX changes :)

1 down, 89 to go, you're welcome 😋

**Comment by joethreepwood** [comment]
#9481 can be closed, as @lottiecoxon did that a little while ago. 

88 issues left.

**Comment by clarkus** [comment]
I worked through my list of open issues in an attempt to find stuff that would have an impact and is also ready for work. I tried to focus on bugs, but there are also small improvements in the list. Here's what I have:

- https://github.com/PostHog/posthog/issues/11337
- https://github.com/PostHog/posthog/issues/10335
- https://github.com/PostHog/posthog/issues/10228
- https://github.com/PostHog/posthog/issues/10227
- https://github.com/PostHog/posthog/issues/10226
- https://github.com/PostHog/posthog/issues/9520
- https://github.com/PostHog/posthog/issues/9241
- https://github.com/PostHog/posthog/issues/9239

**Comment by mariusandra** [comment]
Thanks @clarkus, I added them all to the list above. 

Team, keep in mind everyone that nothing is prioritised at this point... and we still have the rest of _this_ sprint to finish 🙃.

Also keep in mind that even though every 5 solved bugs **will** get you a special surprise, and we will have some bugs that give bonus points, this is not a competition you should gamify. Not at all, nope.

I'll start Monday with further prioritising the list above according to Eisenhower, and definitely not ranking bugs by amount of golden coins you get for each. 

Feel free to start Monday with whatever you find most impactful yourself.

**Comment by pauldambra** [comment]
I think we should probably have this bug on here [multi-dashboard turbo mode confusion](https://github.com/PostHog/posthog/issues/10759)

**Comment by mariusandra** [comment]
I moved the bugs over to a project: https://github.com/orgs/PostHog/projects/58/views/1

Let's continue there!
