### ISSUE TITLE
Split the async server into 3 deployments, each covering one capability

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#12076]
## Description

@macobo's capabilities-based implementation for the plugin server split was A+, allowing us to specify what core internal services (capabilities) a plugin server instance should handle.

Currently, we use this to split between an ingestion server (only covering ingestion) and an async server (covering scheduled tasks, jobs, and exports). 

I would now propose that we split the async server down even further, with one deployment per capability. i.e. after this change, we'd have `plugins-ingestion`, `plugins-scheduler`, `plugins-jobs`, and `plugins-exports`. 

We can ship this for Cloud only and decide later if we'd like to write up a comprehensive runbook for self-hosted users. 

This approach has many benefits:

- Easier for us to debug
- Fewer chances for obscure interaction bugs
- Easier to scale services independently
- Unlocks further lazy loading capabilities, making better use of our resources (e.g. a `runEveryMinute` plugin need not be set up on the exports server)

It does have a few cons too:

- Need to maintain more deployment definitions
- Higher knowledge overhead for team members outside of the Pipeline team?

However, overall I think this is the way forward and will bring us a lot of benefits. It covers #11982, as well as helps with the improvements we'll ship as part of #11784. Brought this up during standup today and there were no objections, so I'll be picking this up when back.

## Tasks

- [ ] New deployment definitions for Cloud
- [ ] Lazy loading for plugins 
- [ ] Deploy on Cloud

**Comment by macobo** [comment]
I'll be off tomorrow but thought to drop a few notes into this thread:

At the moment, the largest difficulty with this is the chart work. Duplicating everything plugin-server related gets kind of ludicrous.

Suggestion on how to solve this problem: Explore using arrays for each deployment with overrides under the main `plugins` object in `values.yaml`. To explain, consider this values file for cloud:

```yaml
plugins:
  # All the config as normal
  hpa:
    minpods: 5
    maxpods: 5
  deployments:
    - env:
        PLUGIN_SERVER_MODE: ingestion
      hpa:
        minpods: 8
        maxpods: 8
    - env:
        PLUGIN_SERVER_MODE: scheduler
      hpa:
        minpods: 3
        maxpods: 3
    - env:
        PLUGIN_SERVER_MODE: jobs
    - env:
        PLUGIN_SERVER_MODE: historic-exports
```

Under `plugins.deployments` array you can specify an array of deployments.

When constructing the manifest, we would _always_ loop over all the deployments, merge the config with the main `plugins` one and create a deployment per item.

In the default self-hosted case, `plugin.deployments: [{}]` - meaning a single deployment with the `default` config as specified under `plugins`.

The goal would be to kill `pluginsAsync` and avoid adding others like it while allowing us to experiment as needed on cloud.

**Comment by mariusandra** [comment]
I initially envisioned that the plugin server itself could do this scaling and load balancing. E.g. you assign it 10 pods/tasks/instances, and it'll load balance the worker/ingestion/etc nodes as it sees fit. I call it "blob mode". 

I vaguely remember reading "re-implementing zookeeper" from some thread, so I assume this approach has been considered and discarded?

(I'm not trying to push this in any direction, just genuinely curious)
