### ISSUE TITLE
Dashboard/Insight Cypress Missing Tests

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#12128]
While working on https://github.com/PostHog/posthog/pull/12067

I had to repeat a number of tests multiple times.

This shows these should be Cypress tests

- [ ] move insight to dashboard
- [x] duplicate insight from insight view (#12350)
- [x] duplicate insight from card list view  (#12350)
- [x] duplicate insight from list view  (#12350)
- [ ] duplicate insight from dashboard
- [ ] remove insight from dashboard
- [ ] add insight to dashboard
- [ ] delete dashboard
- [x] duplicate dashboard
- [x] set card color
- [ ] set card layout
- [ ] update insight data updates dashboard view for that data
- [ ] rename insight from dashboard
- [ ] show or hide legends on insights
- [ ] piechart with show legends has legend on dashboard
- [ ] can select a date filter for a dashboard and then set it back to custom (See #12293)
- [ ] cannot hide table rows in a dashboard InsightTable (see https://github.com/PostHog/posthog/pull/14209)

(some of these might already be)
