### ISSUE TITLE
noisy 'Invalid unit value NaN' errors when parsing invalid timestamp values

### ISSUE THREAD

**Issue by xvello** [PostHog/posthog#13015]
## Bug description

When ingesting events with a valid `sentAt` value and an invalid `timestamp` value, [handleTimestamp](https://github.com/PostHog/posthog/blob/fe494003cc4448fe39442c956b7ba64f1f856623/plugin-server/src/worker/ingestion/timestamps.ts#L20-L34) does not check for the validity of the `timestamp` value, and sends Sentry errors. We do correctly fallback to `now` and ingest the event though.

Indeed, we should:

- fail fast in `handleTimestamp` if the parsing fails
- don't spam Sentry, as it's a data quality issue, not a bug
- surface an ingestion warning instead, and still ingest the event with `now`

The Sentry volume is doubled, because we call this code path twice per event, in both `processPersonsStep` and `prepareEventStep`

## How to reproduce

1. Send an event with a valid `sentAt` value and an invalid `timestamp` value
2. Console logs and Sentry show `Error when handling timestamp: Invalid unit value NaN`

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Action plan

In different PRs
- [x] fail-fast if `timestamp` is an invalid value, stop reporting to Sentry, but still report to statsd
- [x] only report from `prepareEventStep`, stop duplicate reporting from `processPersonsStep`
- [x] report an ingestion warning too (also report if `sentAt` is invalid)
- [ ] [PERFORMANCE] only call `parseEventTimestamp` once, either in `populateTeamDataStep` or a dedicated step, before `processPersonsStep`
