### ISSUE TITLE
Improve efficency of the posthog-event pool

### ISSUE THREAD

**Issue by xvello** [PostHog/posthog#13260]
## In what situation are you experiencing subpar performance?

The posthog-event pool scales too big during peak hours, increasing costs above what one would expect.

## First findings

After adding custom Sentry spans and running a local 50 req/s stress test, here are the typical timings one can observe:

![image](https://user-images.githubusercontent.com/6241083/207026677-214e75ab-7a61-40c7-95f7-cd3b779191fc.png)

This is tracing on **wall time**, not profiling on **cpu time**, we can see in it that cpu-bound operations (event parsing, serialization...) are actually pretty small compared to the rest. The biggest contributors to latency seem to be:

- the middleware chain, especially Axes, which should be disabled on this pool
- `get_event_ingestion_context` (get team span), with one uncached PG request per batch 
- syncronously waiting on Kafka writes (the untagged end of `kafka produce`, plus `kafka wait`): we might be able to tune the producer latency down, but we might hit diminishing returns fast here

I also run some [profiling with pyroscope](https://flamegraph.com/share/18464189-77d5-11ed-b904-9ebeba358f4f) and results are pretty much aligned with the tracing results above.

## Action plan

- [ ] cache calls to `get_event_ingestion_context` with a bounded LRU cache to 
- [ ] skip most middlewares on the posthog-event pool, via a additional envvar in the chart that we'll read in `settings/web.py` to build the middleware chain
- [ ] investigate what knobs the python kafka library exposes to reduce producer latency
- [ ] when ingesting batches, do a single kafka produce call for the whole batch, instead of one per message 
- [ ] discuss transitionning to an async request handler (stack/language TDB), so that request throughput is not linked to Kafka latency

**Comment by macobo** [comment]
>the middleware chain, especially Axes, which should be disabled on this pool
Note that Auto Project middleware is also a safe kill for this :)

**Comment by tiina303** [comment]
> skip most middlewares on the posthog-event pool, via a additional envvar in the chart that we'll read in settings/web.py to build the middleware chain

Don't think we need an envvar for that, people can use web + events or just web pods in the chart, anyone using events pods will want the same thing for them to be as light as possible

**Comment by xvello** [comment]
> Don't think we need an envvar for that, people can use web + events or just web pods in the chart, anyone using events pods will want the same thing for them to be as light as possible

Most middlewares are skipped when calling the decide endpoint, because of [ShortCircuitMiddleware](https://github.com/PostHog/posthog/blob/3a9e0370cd024b3407c6a3937038e87fa104d5db/posthog/middleware.py#L188-L196). I could add checks for the three capture endpoints, but:

1. that looks a bit kludgey to me
2. it breaks the prometheus django instrumentation, as `PrometheusAfterMiddleware` is skipped

Instead, I'd rather change the code [building the middlewares list](https://github.com/PostHog/posthog/blob/3a9e0370cd024b3407c6a3937038e87fa104d5db/posthog/settings/web.py#L42-L72), and have it produce a much shorter list for pods in the `posthog-event` deploy. This is where having a new `POSTHOG_HEADLESS_ENDPOINTS` envvar would help. The `posthog-web` pods (and the hobby deploy container) would keep the full middleware list as the envvar is not set.

Because most of these middlewares are security, we could also disable all but the capture & decide endpoints when that envvar is set.

WDYT @tiina303?

**Comment by xvello** [comment]
## Production traces

I found [a couple](https://sentry.io/organizations/posthog/performance/posthog:cf6fb2819f5343c2abc571abfb9f71ec/?project=1899813&query=&referrer=performance-transaction-summary&statsPeriod=30d&transaction=%2Fcapture%2F%5B%23%5D.%2A&unselectedSeries=p100%28%29) [of traces](https://sentry.io/organizations/posthog/performance/posthog:4a562c05f12345ef8dc595343e8cf373/?project=1899813&query=&referrer=performance-transaction-summary&statsPeriod=30d&transaction=%2Fcapture%2F%5B%23%5D.%2A&unselectedSeries=p100%28%29) [in prod](https://sentry.io/organizations/posthog/performance/posthog:5b5eebd150e14612b5e330d93f92b51c/?project=1899813&query=&referrer=performance-transaction-summary&statsPeriod=30d&transaction=%2Fcapture%2F%5B%23%5D.%2A&unselectedSeries=p100%28%29) that passed through the sampling and rate-limiting. They show a pretty similar shape, although the contribution of the Kafka produce latency is lower (yay for quick wins while staying sync):

![image](https://user-images.githubusercontent.com/6241083/207042820-97becd95-0bcf-4d59-8af4-c503da5f9469.png)

## Multi-threaded profiles

My initial measurements were done with a single-threaded django executor. Moving to 2*8 threads like in prod with `DEBUG=1  gunicorn posthog.wsgi --bind 0.0.0.0:8000 --workers=2 --threads=8 --limit-request-line=16384` gives the following profiles: https://flamegraph.com/share/be4a89c7-7a24-11ed-93e3-ca690ab2bec3

  - `get_event_ingestion_context` and middlewares do contribute to the CPU usage and should be optimized out
  - structlog has a pretty heavy 15% CPU footprint (acquiring a lock it seems?). Would switching log level from info to warn help on cloud, or do we rely on these logs? 
  - `json.dumps` is pretty small on my test bench (although the json payload is 1.5kb uncompressed), not worth optimizing for now

**Comment by xvello** [comment]
## Kafka producer

We use the (almost) pure-python [kafka-python][https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html] library. Because its high-level API only allows to produce one message at a time, we unpack event batches, and do one `produce` call per event. Worst case scenario, that's one Kafka ACK per event.

This producer does implement batching, through the `batch_size` and `linger_ms` settings. Setting a small (5ms? 10ms? To be tested) linger might help reduce load on both the producer and the Kafka brokers, with the drawback of potentially increasing latency for single-event requests. Our django containers currently run with 2 gunicorn workers, each spawning 8 threads. The Kafka producer is a singleton shared between the 8 threads, which could help make the producer batching strategy more viable.

Alternatively, Confluence maintains another [python client](https://docs.confluent.io/kafka-clients/python/current/overview.html) that wraps the native `librdkafka`, and could be more performant, but that's a pretty disruptive change (different API and failure modes).

**Comment by xvello** [comment]
## Load imbalances within the posthog-events deploy

We do have a significant imbalance between pods [[grafana dashboard]](https://grafana.us-east-1.prod.posthog.dev/d/4pXqk9KVk/events-capture-efficiency?orgId=1&from=now-7d&to=now). We run 2*8=16 gunicorn threads per pod, on prod-us we have some pods plateauing at 5 and some hitting 16). We need to address this before being able to set more aggressive HPA settings and downscale.

![image](https://user-images.githubusercontent.com/6241083/207832481-f11d2662-9fd8-40db-88e8-bd44cba65493.png)


Looks like we are using the default `round_robin` balancing strategy, which does not play nice when request processing times are not identical. Ideally, we’d use `least_conn`, but it’s not currently supported by ingress-nginx ([see issue](https://github.com/kubernetes/ingress-nginx/issues/3659): they re-implement load-balacing in lua to have a dynamic target list without reloads. There’s an [implementation PR](https://github.com/kubernetes/ingress-nginx/pull/9025) open though, so :crossed_fingers: ).
The only alternative they currently support is [ewma](https://technology.lastminute.com/ingress-nginx-bug-makes-comeback/), which still assumes query cost is uniform, but will still fare better than round robin. Opened [a thread with infra](https://posthog.slack.com/archives/C045QJCUGQ4/p1671097320953449).

**Comment by xvello** [comment]
Closing now as the proposed changes have been implemented and capture.py is in a better state now. No further work is planned, as https://github.com/PostHog/capture/ is slated to take over that scope.
