### ISSUE TITLE
[EPIC] Move to ClickHouse

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1406]
## Process Overview
Modified by @EDsCODE 2020-8-17
Modified by @Twixes 2020-11-15

We will use this ticket as an index for the different parts of the move. When working on a bullet point, link a new PR or issue to demonstrate solution/continue discussion. 

### Initial Setup
We will do some initial verification of how key parts our current system will work on clickhouse.

- [x] @EDsCODE Event Schema for property filtering
- [ ] @EDsCODE Event/Action Schema for action calculating
- [x] @fuziontech Develop method to easily test on high volume instance
- [x] Person/DIstinctId schema for clickhouse
- [ ] @fuziontech Document local environment for dev

### Interfacing
Developing the foundation for how to coordinate between multiple databases

- [x] Restructure backend to accomodate different database configurations (just postgres or postgres + clickhouse)
- [x] Configure and deploy production cluster of clickhouse
- [x] Set up migrations and schema
- [ ] Create plan for later feature that allows users to migrate from solo postgres to a clickhouse cluster (we may decide this will always be an involved process and not easily doable following docs)
- [x] Create skeleton for where all the new clickhouse queries will be live

### Refactor (TBD)
- [x] Rewrite all queries

EDIT: crossing off the previous plan below in favor of the above

~~## Jobs to do~~

~~- [ ] @ungless Generate list of keys for posthog js~~
~~- [ ] @ungless Take those keys and generate schema~~
~~- [ ] @fuziontech Test funnel query~~
~~- [ ] @fuziontech document local environment for dev~~
~~- [ ] @timgl Set up migrations and schema~~
~~- [ ] @timgl Add all event queries to /queries folder~~
~~- [ ] @timgl Rewrite all queries into new folder and create way of easily switch between ClickHouse/Postgres~~
~~- [ ] @fuziontech Set up real cluster~~
~~- [ ] @fuziontech Migrate openrent~~

## Questions
-  How do we do migrations? A: [python driver](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/schema_migrations.md#schema-migrations)

**Comment by timgl** [comment]
Based on meeting we had today (video incoming) we've decided to go with a pure clickhouse SQL route, where we replicate all `queries` files.

Some open questions:
1. How are we recalculating actions? Partitions seem to be the answer.
2. How do we do testing? Integration tests?

**Comment by Twixes** [comment]
Would testing as it is now be insufficient? The output data should be the same regardless of the DB. Is there more to this than that?

**Comment by EDsCODE** [comment]
[This branch](https://github.com/PostHog/posthog/tree/clickhouse-setup) is the base setup for clickhouse. It includes a preliminary working organization of clickhouse related functionality. All the tasks below should be a branch off of clickhouse-setup. Our final should be a single merge from clickhouse-setup into master. 

**Current tasks**

Base:
- [ ] Implement Actions mechanism (either materialized view or precalculation) (@fuziontech)
- [ ] Implement cohort mechanism
- [ ] adapt demo data to fill clickhouse

Queries:
- [x] [Trends Query](https://github.com/PostHog/posthog/tree/ch-trends-basic)
- [x] Stickiness (could be added to above)
- [x] [Sessions](https://github.com/PostHog/posthog/tree/ch-sessions-basic) (@EDsCODE)
- [x] Paths
- [x] [Retention](https://github.com/PostHog/posthog/tree/ch-retention-basic) (we have the query but didn't integrate into API yet)
- [x] Funnels (@fuziontech) 

Nice-to-have
- [ ] better delineation or documentation where ee licensed features will be inserted (right now it's very adhoc)

**Comment by Twixes** [comment]
Mostly done! 🚀 I suggest making separate issues for any particular things left (documentation? demo data? action calculation? easy migration from Postgres? don't have enough context, but paging @EDsCODE @fuziontech) and closing this epic to make addressing the last bits easier.

**Comment by timgl** [comment]
Closing as we have moved to Clickhouse.
