### ISSUE TITLE
Planning Document: Early Access Feature

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#15055]
Owner: @EDsCODE 

### Context

**What are we building**

Beta feature management MVP. A system that allows users of Posthog to easily implement a beta management control panel where their users can opt in to feature previews.

**Why are we building this**
(TBD: Add more context here)

**What to do with this ticket**
This is an overview ticket so everyone participating can understand what we’re building, why decisions are made in such a way, and what needs to be done.

### Revised Details

**Problem**
Posthog user/team wants to give their end users the option to opt-in/opt-out of a feature flag

**User flows**
1. Posthog User wants to directly test a new feature publicly.  
2. Posthog User wants to test a feature flag that currently exists publicly.

**Solution**
An early access feature scene where Posthog users can make a feature flag publicly accessible.

**Features**
1. An "early access feature" can directly create an underlying feature flag—like an experiment.
     <details>
     <summary>how it works</summary>
     Creating an early access feature will implicitly create a feature flag with a person property condition $feature_enrollment/<feature flag key>
     </details>
2. An "early access feature" can link to an existing feature flag. (only boolean for now)
     <details>
     <summary>how it works</summary>
     Creating an early access feature will add a person property condition $feature_enrollment/<feature flag key> to the flag that's specified
     </details>
4. User membership in an early access feature can be revoked manually
5. The "early access feature" can be labeled with a beta stage or general availability (with option to extend later). Beta = end users can freely opt-in, opt-out. General Availability = 100% rollout
6. Posthog users will be given the option to develop a UI to toggle these features using our client lib APIs OR using a site app that provides a prebuild widget. 
     - API: getEarlyAccessFeatures (new), updateEarlyAccessFeatureEnrollment (new), isFeatureEnabled (exists) 

**Important notes**
1. The early access condition. This condition is a _super property_ which means it takes precedence over existing conditions. Flag evaluation will check first for super properties. If none exist, evaluation will proceed normally with existing release conditions. If a super property does exist, whatever bool it evaluates to is final. This is necessary to smoothly transition users matching existing conditions of existing flags into the opt-in/opt-out functionality. 
     - Example: Consider a user A that matches an existing condition on an existing flag X. Also, consider that we do not have a concept of super property. Suppose that flag X is connected to an early access feature and now user A has the ability to opt-in/opt-out. The toggle presented to user A will be denoted as "enabled" upon the start of this connection. Suppose that user A toggles off the feature. The toggle will set the person property to false. However, because all conditions are evaluated equally as OR'd together, the toggle will still show "enabled" because user A still matches the existing flag conditions. 

       With a super property, if there's no property set on user A, evaluation will default to the existing condition and show "true". Once user A starts toggling, all state will be deferred to user A's manually set preferences which ensures clearest user experience. 
3. Early access features will be default 'Beta' upon creation.

<details>
<summary>Prior planning</summary>
**What’s been done so far**

- Hackathon result: https://github.com/PostHog/posthog/pull/14952
    - Created a new scene for features and feature management
    - Feature page where you can create a “feature” that will link to a new feature flag
    - Working concept for filtering/populating decide with featurepreview data
  

**What needs to be done**

For each todo list item, please assign yourself if you're tackling it and link the PR that’s in progress or link a separate ticket if it needs more discussion. _Do not just add comments to this ticket. List important questions under “open questions”_

Backend

- [x]  Move site_apps and featurePreviews into a separate endpoint to isolate /decide workload @neilkakkar 
    - Why: Resiliency of decide endpoint for feature flag matching
    - Additional consideration: Make sure this endpoint is rate limited as it will be publicly accessible
-  [ ] Add decide property overrides to posthog-js so we can prevent ingestion delays with opt-ins which will occur here: https://github.com/PostHog/posthog-js/pull/604 @neilkakkar 

Frontend

- [ ]  Design and implement site app that will give access to turning on and off features to participate in? Or determine alternative integration plan. Include instructions in UI as an option alongside manual integration
- [x]  Make a decision on what fields to include when creating a “feature” @EDsCODE (https://github.com/PostHog/posthog/pull/15099)
- [ ]  Make a decision on whether or not you should be able to attach existing flags onto a feature for MVP (Neil: I don't think this will be very useful without this, so I'd say yes) @EDsCODE (https://github.com/PostHog/posthog/pull/15099)
- [ ]  Provide analysis data on the feature page for the performance of the feature?
    - Examples: persons opted in count/trend graph
- [ ]  Improve integration instructions. Code examples are only half the instructions needed. Users need to know how to manually implement the feature preview workflow or integrate the siteapp
- [ ] Implement ability to add/remove person from a person list on the management page @EDsCODE (WIP: https://github.com/PostHog/posthog/pull/15099)
- [ ]  Add event tracking to switching on and off the feature (Neil: This should interplay nicely with the event setting the person property, not sure how this should work)

Release
- [ ] Gather interested beta user list 
- [ ] Create experiment that tests feature previews as a tab under a feature flag or as a separate scene/nav item
     - [ ]  Move/rename navigation buttons for feature flags + features “feature management” https://github.com/PostHog/posthog/pull/15056

**Open questions**

- What do we name this "feature"?
     - @lharries votes "Beta management"
- Do features get closed/archived at some point when it reaches general availability?
- The stages don't yet make sense to me. Why do we have stages?
     - Answer: Just do beta/general availability right now
- Do we want to support multivariant flags?
- Payloads for extra flexibility sounds good. Do we want this to be the de-facto interface though? (pro: works for ios/android/js out of the box, a LOT more flexible; cons: is harder to use, janky)
     - Answer: Not using payloads for fields
- Should matching persons on this special property just be out of the box functionality for feature flags?
- Handling groups?
- **Using person property matching will disable any bootstrapping that can happen which may make the experience really inconsistent/flickery if a user logs in/comes back because person properties won't be loaded**

</details>

**Comment by annikaschmid** [comment]
Feedback from @joesaunderson on this feature:

> I had some additional ideas on this actually, if you’re introducing the concept of “features” into the app, could this encompass multiple flags?
I.e I am building a new feature, which has multiple parts (multiple flags) - but all of these feed into the top level “feature” in PostHog.

**Comment by annikaschmid** [comment]
If we want to split out feature management from feature flags as part of this change, I have written up some further thoughts here: https://github.com/PostHog/product-internal/pull/472

**How a PostHog user would enable this for their users?**
The idea of the hackathon was to provide the data via API, and then the user can handle the styling. From one user interview, they wanted to have the flexibility of having a "feature preview" page somewhere in their product (like GitHub), but also having banners on the relevant product pages where the user could opt into a new feature, for "less technical" users (users less familiar with GitHub's feature previews).
I kinda like the idea of having a site app in addition, but would prioritise the API.

**Do features get closed/archived at some point when it reaches general availability?**
Our idea during the hackathon was that a feature can be in 4 states: Concept, Alpha, Beta and General Availability. Here is a Figma file that very roughly outlines the functionality in the 4 phases: https://www.figma.com/file/YYhH6adljnzyROEaSK5WqQ/Feature-Management-Hackathon-UI?node-id=202%3A2366&t=SzoLA7W4MDhhA5bd-1

The idea of the concept stage was to power our public roadmap. I think we can skip Concept for now and potentially merge Alpha and Beta. The only thing "General Availability" would really do is roll out the feature to everyone. Archiving it would only make sense if we don't extend the 'Feature Management' with additional functionality (see Features RFC). e.g. if we have feature analytics and feature feedback, then the feature should not be archived for GA.

This was the marketing text we had prepared for the website:

# Feature Management

## Power your public roadmap
### List features on a public roadmap to show your users what you are working on.

### Custom UX
Create the UX and let our API handle the content

### Group features by stage
In Consideration, Alpha, Beta? Show your users in what stage your feature is.

## Create a feature waitlist
### Allow users to subscribe to a feature waitlist to register interest

### 1-click subscriptions
Users can subscribe to your waitlists right from within your product

### Manage your subscribers
See which users have subscribed to your waitlist, and add or remove users manually

## Choose who gets access to features
### Release Alpha features to internal or selected external testers

### Granular rollout conditions
Use release conditions to choose who gets access to a feature, for example by targeting by user ID, email address or cohort

## Allow users to turn on feature previews
### Let users opt in and opt out of Beta features from anywhere in the product

### Self-serve beta testers
Users can turn on Beta features with one click, no manual steps needed',

### Custom UX
Create your preferred experience for handling Beta opt-ins, powered by the PostHog API

___

**Here are the interview notes from speaking to a customer in October, who have built a very similar tool in-house:**

Feature flags in their main product:
They have built a internal tool for feature flags in desktop app
Neil to show him how to use experiments without feature flags
Postgres source of truth for their users
This is why they use an internal tool, it’s ‘safer’ to identify the right people
How their internal feature flags tool works:
A user can opt in during their onboarding to use a specific feature
This goes into a list, where his team can decide which people to give access to new features
They have a retool setup for for this, where they can see who wants to use it, and they can invite them, this sends them an email invite and enables the feature flag
They can also give people access to new features through a user search
How the decision was made to build an internal feature flags tool
Spoke to lots of feature flags tools
All were very pricy
This is why they built their own tool
Took 1-2 weeks to set up
Most of the value is from the invite management, not the toggles, this is why they decided on build vs buy
Already had infra for user settings, so it was quick to set this up

**Comment by EDsCODE** [comment]
**Update:**

Some learnings when working through the beta management site app the past few days. Apart from a cumbersome testing workflow (until app-dev-server is updated). There’s a handful of gotchas that makes this pretty complicated for a user to implement themselves

- Error handling is very unclear. The client lib functions provide no guarantees because we’ve made them to be fire and forget. If ingestion is down or backed up, you can very easily end up in a mismatched state
    - The point seems most troubling as there's no strong guarantee for consistency here. User will expect that the new feature is available on refresh so the flag has to locally overridden. If the event to update user property ever drops/fails, we'll end up in an inconsistent state and the client will just have to keep trying to send the event. If the cache is ever lost, the user will reset their state
- getEarlyAccessFeatures should probably always be “force_reload”. When it’s not, the local state can decouple from server state
- The filtering that needs to happen to “get users who are part of an early access release” is mismatched. On the client library we use “isFeatureEnabled” but on the management scene, we need to use a person search for persons with the property set. This is unreliable because you can have the property set but the flag may be disabled or the values may change, etc. You can end up in a state where the feature management scene shows the user is in the release group but it’s not actually visible because the flag itself is disabled
- For the user, it can be really jarring if your toggle says false but the flag has another condition that's something like "release to 100%", then the release group property is useless
     - early access feature should have a high priority property that takes precedence over all other release conditions

**Comment by neilkakkar** [comment]
> (until app-dev-server is updated)

Explain? 🤔 

---

This makes a lot of sense! Some ideas:

1.  This is same as losing events / losing property-updates - which should be pretty rare. But if it does happen - indeed is a problem. I don't think we should worry about this right now though: and assume it will go through; _or_ result in an experience where the client will have to manually re-enable the beta.
2. Hmm, I see the problem. The reason it's not always force reload right now is because you may want to use this in a component / something that re-renders often, where re-loading wouldn't make sense. Mismatch between local & server state is also not a problem: just means you can't see the new features coming in. But actually, I guess people who want things to re-render can just call this once and save the results. Makes sense - less surprising interface like that. Yeah, let's get rid of force_reload, doesn't need to be stored in local storage. Got to give some error handling here though, for when requests fail.
3. We should change the semantics here. The list shows: "People who've chosen to opt in" to this feature. Make it explicitly clear that this doesn't mean the flag is enabled for them, because that's in your control. All it means is people who _want_ to be in the feature. "If you want to check if the flag is enabled, click on person -> go to flags tab -> see why" (or make this automatic link to the right place)
4. In a similar vein to (3), I don't think we should introduce this concept of high priority property. What we need instead is a workflow for going from beta release to general availability (100% rollout). I'm not quite sure how this should look like. An idea might be (a): warning users when they add a 100% release condition & the beta feature stage is not general availability. (b): Hiding features in general availability stage from feature preview. As a combination of both these things, the end users can't see this general availability feature anymore, and can't opt-out of what the posthog-user doesn't want them to opt out of.

**Comment by EDsCODE** [comment]
"Choosing to opt-in" should entail fully having accces. The waitlist/approval pattern is supposed to be specifically if the feature is labeled as "alpha", but if it's an open "beta", an end-user opting-in should just mean that they have access.

For (4), the problem can be even more subtle. If a flag already has some conditions that releases the feature to X people, when this flag is linked to public access, do these X people now get to toggle things on/off, rendering the original conditions deprecated or do only the new set of Y people who never got the flag in the first place get to toggle

Going back to super property: I do think there has to be some sort of overriding/super property behavior. When a flag is an early access feature, this flag is "public" which means the evaluation criteria should go `public condition (the feature enrollment property)` -> regular condition. Public conditions will have precedence and we can gray out the release conditions when public conditions are in effect. This way the toggle powered by isFeatureEnabled that users are presented will always be in sync with the public condition that the end user experiences. If you ever need to disable the public release, it can easily revert back to the release conditions that previously existed

**Comment by EDsCODE** [comment]
> > (until app-dev-server is updated)
> 
> Explain? 🤔
> 

https://github.com/PostHog/app-dev-server This thing needs to be published so I can test new posthog-js functions on the site app more easily

**Comment by liyiy** [comment]
> If a flag already has some conditions that releases the feature to X people, when this flag is linked to public access, do these X people now get to toggle things on/off, rendering the original conditions deprecated or do only the new set of Y people who never got the flag in the first place get to toggle

I think if a flag is in beta release stage that should always mean the end user should have the final control of whether they want it enabled or not. If you roll out a beta release to 100% people then everyone should have the option to toggle? What did you mean by original X people vs new set Y people? Why does there need to be a differentiation? 🤔 

> For the user, it can be really jarring if your toggle says false but the flag has another condition that's something like "release to 100%", then the release group property is useless

Using the release management system, I would just assume the feature flag's rollout condition if it's linked to a "feature release" just means that for that whichever stage of feature release it's in, that's the release conditions for that stage.

**Comment by EDsCODE** [comment]
> I think if a flag is in beta release stage that should always mean the end user should have the final control of whether they want it enabled or not.

Yep, agreed. There shouldn't be differentiation. I think I should draw out the exact case where things can fall apart that make it confusing.

For example, let's say a user A can see a feature flag because they match the conditions that are set. Then, we make that feature flag an early access beta. Now user A can toggle the feature on and off on their own. However, because "early access features" simply rely on a specific person property condition which is just another release condition, the interface can end up in a scenario where: user A matches the original release conditions, toggled the feature toggle to "false" which means their feature enrollment person property is false, but the flag is still showing up because the release conditions are OR'd together.

**Comment by neilkakkar** [comment]
> I think if a flag is in beta release stage that should always mean the end user should have the final control of whether they want it enabled or not.

This is where the contention lies. I don't think this should be the case. And we should validate this before building super properties.

Here's how I'm thinking about this:

Case 1: I want to let users control beta opt-in/opt-out
In this case, I just have one condition on the flag.

Case 2: I want to let some eager users control beta opt-in/opt-out; but also incrementally keep releasing for others
In this case, the option does not work for users we've "force-enabled" using a second condition.
Where this makes sense:
1. Releasing internally for testing, dogfooding.
2. If an org/co wants all their users to be in the beta, we can control that.

Case 3: A user who has been forced into the beta wants to opt-out
This is not supported.

---

Whereas what you're suggesting is Case 1 & Case 3 are supported, but case 2 is not supported.

Hmm, I can see good reasons for both. We _could_ support all three, but at this stage it's more complexity that's not worth it.

The case for supporting Case 3 I can see is something like: "By default, I want to opt in specific users coming in to the system for this feature, and then let them opt out if they want". This lets them see the feature, and then decide to opt out if they wish.

I think this is a minority compared to case 2, and is possible to support out of the box without super properties; by default the developer can set enrollment status when a person logs in / use a second feature flag to choose conditions on which to enable this; and then let the user themselves control it. I.e. case 3 is supported not by changing conditions on the flag, but by calling `setEarlyAccessEnrollmentStatus()` - using person properties.

---

The reason I don't yet want super properties is because it introduces a new complicated feature on flags that needs:
1. UX explanation
2. new evaluation reasons explanation
3. Updating local evaluation in all libs, so results are consistent

for a seemingly not-convincing(in my eyes, for now, open to change) use case.

**Comment by neilkakkar** [comment]
Thought about your original message a bit more, one weak counter point to (2): `force_reload` on `getEarlyAccessFeatures`: When in a pure posthog-js environment, it can get pretty annoying for a user to have to control state using local storage / cookie, such that every time a person visits the early access page, they don't request for available features again. Fine to go either way, your call!

**Comment by neilkakkar** [comment]
Had a sync chat: I was wrong! Core component here seems to be Case 3, rather than 2. I'm more in favour of end-users being in control now - it makes a TON more sense UX wise, and reduces confusion for our user's users.

We'll start with a small change to validate; focus on the UX - explain how this overriding works; disable local evaluation.

**Comment by EDsCODE** [comment]
**Update:**

Initial MVP released internally

Open PRs:
- [Docs PR](https://github.com/PostHog/posthog.com/pull/5941)
- Tests and logic for rollout 100% https://github.com/PostHog/posthog/pull/15506

TODO:
- Continue to QA. State management between app and feature flags is still iffy
- Delete/archive. There needs to be a mechanism for closing early access features that have finished their beta run
- Add beta tags?
- Possible bug: It seems there may be some state inconsistency. If an early access feature is available for toggling, the feature flag is active but the toggle appears off
- Release to % of users and collect feedback

**Comment by neilkakkar** [comment]
Some more things to fix:

1. Use the FeatureFlagSerializer to create, so we handle logic around deleted flags being re-used.
2. When creating a new flag for early access, by default roll out to 0% instead of 100%.
3. I can soft-delete a feature flag that's connected to an early access release. We should enforce deleting early access -> delete flag ?

**Comment by neilkakkar** [comment]
Hmm, thoughts on not soft-deleting early access features? Just like experiments, these depend on flags existing & don't really have much stand-alone to recover. This will also mess with database constraints / figuring out how to soft-delete a flag with a soft-deleted early access feature.

**Comment by EDsCODE** [comment]
+1 hard delete features

**Comment by annikaschmid** [comment]
Some thoughts from a UX perspective:

Easy:
- The feature is called "early access management" in the navigation, but the breadcrumb and URL say "early access features". It should be called "early access management" everywhere
- The copy "Release features in a controlled way. Track adoption in stages." is very undescriptive. It doesn't really differentiate this feature from feature flags. Instead, we should say something like "Allow your users to enable or disable features that are in public beta. Check out our [Early Access Management user guide](https://github.com/PostHog/posthog.com/pull/5941/files) to learn more." 
- The "Implement Public Opt In" button on the new release page should be linked on the overview page as well I think
- The copy in the "Implement public opt in" popup needs some wording streamlining as well. The headline says "How to implement opt-in feature flags", then the text says "Implement manual release condition toggles" and "opt-in to features". Similar to the point above, I think we should agree on copy that makes it clear it's not affecting the feature flag, so no "feature flag" or "release condition" wording

Medium:
- I am unsure whether the button "new release" makes sense, because that's not how the feature is called and I want to differentiate it from feature flags. We could say "New public beta" or something?
- On the "New feature release" page, I can select an existing flag (optional). That means if I don't select an existing flag, it will create a new one for me, right? That is not particularly clear to me, the tooltip seems to indicate that a flag is created by default aka at all times
- Once I selected a flag, I can't remove it anymore

Hard:
- Have we ever had the conversation whether where a feature should be promoted to general availability? Right now I can do that both on a flag and on a feature preview. That can result in features that are promoted to GA on the feature preview, but only at e.g. 20% on the flag. I think it would be easier for now if we let feature previews just handle public betas, and all other rollouts will be handled via the feature flag. That means no "General availability" setting on early access
- If we decide to keep a "promote" feature, it should be called "release / promote to general availability" and the user should be able to recover from this / roll it back. My preference is we kill this button and only allow rolling out and rolling back features to GA via flags
