### ISSUE TITLE
Persons-on-events V2 Checklist

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#15178]
A checklist of things we still need to do before enabling PoE v2 for everyone:

- [x] https://posthog.sentry.io/issues/3918069788/?query=is%3Aunresolved+CH&referrer=issue-stream&statsPeriod=14d&stream_index=19 @yakkomajuri 
- [x] https://posthog.sentry.io/issues/4102203928/?project=1899813&referrer=slack @yakkomajuri 
- [x] `plugin_log_entries` ghost part issue (non-blocking but would be good to handle) @yakkomajuri 
- [ ] Mechanism for flipping back to normal queries early on @yakkomajuri: #15459 
- [x] Checking cohorts in PoE v2 @yakkomajuri 
- [x] #14782 @tomasfarias 
- [x] Performance benchmarking @yakkomajuri 
- [ ] PoE v2 writes for everyone @tiina303 
- [ ] Backfill async migration @yakkomajuri 
- [ ] #15120 (non-blocking) @yakkomajuri 
- [ ] Docs & communication

**Comment by yakkomajuri** [comment]
- Follow ups to plugin_log_entries issue: metric, EU cluster check
- Team that should aggregate by distinct ID is somehow on PoE v2

**Comment by yakkomajuri** [comment]
- Actions

**Comment by tkaemming** [comment]
This is all done!
