### ISSUE TITLE
S3 backed recordings follow up work

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#15200]
## TODO list
(Many TODOs are in the code as well)
- [x] @benjackwhite  Setup helm chart work https://github.com/PostHog/charts-clickhouse/pull/726
- [x] Setup S3 bucket with lifecycle policies (https://github.com/PostHog/posthog-cloud-infra/pull/1477)

## Follow up PRs
- [ ] @pauldambra  - Writing of minimal data to new Clickhouse table (and grouped materialised table) - listing from Clickhouse
- [ ] @pauldambra - Playback of persisted S3
- [ ] @pauldambra - Redis as offset tracker for sessionID offsets
- [ ] Reading of in-progress recordings
- [x] @benjackwhite  Modify loading from "metadata" endpoint to no longer include snapshot info as we won't be easily able to query it anymore
- [ ] Load testing (script to run which will ingest multiple parallel dummy recordings at once)
- [ ] We are relying on offsets which are Int64 - how does this translate in JS...?

## Thoughts

Using redis to track sessionId offsets means ~2million IDs ([see metabase](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjM2LCJhZ2dyZWdhdGlvbiI6W1siZGlzdGluY3QiLFsiZmllbGQiLDI5NSxudWxsXV1dLCJmaWx0ZXIiOlsiYW5kIixbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDI5NyxudWxsXSwtMSwid2VlayIseyJpbmNsdWRlX2N1cnJlbnQiOmZhbHNlfV1dLCJicmVha291dCI6W1siZmllbGQiLDI5Nyx7InRlbXBvcmFsLXVuaXQiOiJkYXkifV1dfX0sImRpc3BsYXkiOiJsaW5lIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) each with a kafka offset (Int64?) so

**Comment by pauldambra** [comment]
> Writing of minimal data to new Clickhouse table (and grouped materialised table)

## Why do this?

It's expensive to list and query session recordings

We materialize several columns, one of them (event_summary) is based on $snapshot_data, the others are based on event_summary. We want to stop storing snapshot_data in ClickHouse, so we can't use it to materialize data in CH #Ouroburos

## scratchpad

we want:

* unique session id
* latest distinct id
* start timestamp
* end timestamp
* therefor duration
* start url (first url in the merging)
* click count
* keypress count

see https://github.com/PostHog/posthog/blob/master/posthog/models/session_recording_event/sql.py
see [_core_session_recordings_query](https://github.com/PostHog/posthog/blob/ed406b899ee7993717dcabe984cde120d3a367fa/posthog/queries/session_recordings/session_recording_list.py#L73)

-----
