### ISSUE TITLE
Exception tracking but better

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#15691]
## Is your feature request related to a problem?

We want a good way for you to automatically get useful information about errors in your product when using PostHog

Captured as events to match the existing sentry integration and to give all the benefits of our tooling and features around events

We want to enable this without causing ingestion volume to rise too quickly. And we want to minimise the impact of any rise in ingestion volume as much as possible.

If we work on this our first goal will be to turn this on for PostHog and a few reference customers to get their feedback.

## Prerequisite before turning on

Separate ingestion deployment as we did for replay ingestion. We have /s/ and /e/ this could be /x/

## what is it?

* exception autocapture from posthog-js, controlled by a toggle in project settings
* manual error capture from posthog-js using an SDK method
* good (but not great) error and stack trace display in event tables and alongside recordings
* dashboard template for errors
* documentation
* slow roll-out so we can learn its impact on ingestion and for customers

## what else might we need

* rate limiting in the SDK to for e.g. stop a high volume of errors being emitted in a loop
* suppression of errors by pattern - e.g. we get a lot of resize observer errors that we know we don't care about

-----

Description from the previous run at this ⬇

## Describe the solution you'd like

Autocapture for errors in PostHog-js (codename AFEIPJS)

* We already gather `Exception` events if you use the Sentry integration. We'll use this same event and autocapture errors into that event type. 
* When using the Sentry integration we will keep the same fields but also map them to our error fields
* because they're events they can go in insights
* because they're events existing recording filtering can use them
* we can make a dashboard template for error tracking
* we'll add this autocapture as one of the super powers so that it is on by default for new customers

- [x] review open source SDKs to learn about edge cases like throttling or grouping if people have errors in a tight loop
   - [ ] could e.g. send a different event when throttling so we can highlight these to users
- [x] add autocapture for errors and config to enable/disable to PostHog JS
- [x] decide data structure we'll send
- [ ] can we surface quick counts alongside replay summary listings
   - [ ] e.g. a materialized aggregation of session id, error type, error count

## Additional context

example data structure

```
{
    type: string,
    group: string // allow automatic grouping of similar events
    mesage: string,
    handled: boolean,
    sessionRecordingURL: string,
    sessionId: string,
    originalStackTrace: Record<wat, who, which>,
    stackTrace: SomethingFlatSoWeCanFilterAndSearch?
}
```

**Comment by pauldambra** [comment]
- [x] exceptions in the listing alongside session recordings
- [x] pretty display of stack traces in listings and tables
- [ ] ability to filter/analyse exceptions

**Comment by pauldambra** [comment]
we've done a big chunk of this and aren't going to go further right now
