### ISSUE TITLE
Team Monitoring Q3 2023 Megaissue 🤘

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#16287]
# Team Monitoring Q3 2023 Megaissue 🤘

Previously on the Megaissue: [Q2 2022](https://github.com/PostHog/product-internal/issues/456), [Q1 2022](https://github.com/PostHog/posthog/issues/13393), [Q4 2022](https://github.com/PostHog/product-internal/issues/354)

This is designed to be a focus point to link together what we plan to do, feedback on that plan and progress as we go forward.

It is **not** meant to be discussion about individual features. As soon as the discussion starts a dedicated feature issue should be created, added to the roadmap and discussed there.

# Goals

#### 🎯 Goal 1 : Notebooks on ProductHunt
**Why?** - We are building more and more of the Product OS and covering a wider range of product engineering tools. The challenge is in bringing all these things together. We trialled the concept and are sure this is the way to go. Now it's about making a slick experience where you can explore all of PostHog's content in one place, collaborate and share with others.

* We want to rollout notebooks to everyone
* This means setting and reaching a certain quality bar ASAP
* So that we can confidently push out to the world

#### 🎯 Goal 2 : Next 5 great things for Replay
**Why?** - We have users who love replay and have it as a core part of their workflows. We want to work on the top 5 most impactful changes based on what the community is asking for. Notebooks will partially improve Replay by allowing commenting and collaboration but it is not the only thing that could make Replay even better.

* _(Below are Ideas that need to be validated with customers - i.e. via roadmap perhaps?)_
* [Network request and response capture](https://github.com/PostHog/posthog/issues/16410)
* Better Filtering via quick search / simpler UX / NLP etc.
* Annotations support (deployment info)
* [Replay Clips - with gif/video exporting](https://github.com/PostHog/posthog/issues/16412)

## Side Quests
- [ ] 😍 **Toolbar 3000**: [UX redesign](https://www.figma.com/file/uNuL5XDnOqasYuK0yfpnmV/PostHog-3000?type=design&node-id=1992-63659&mode=design&t=sXEeEuh89rVrLvI9-0) to fit with the app 3000 work.
- [ ] 🤔 **Heatmaps 3000**: Currently we actually have click maps - partly we should make this clearer and more performant, also we could extend the feature using Replay data to have an actual heatmaps.
- [ ] 😏 **Mobile Session _Monitoring_**: Replay here has a lot of challenges and privacy issues that led us to deprioritise it. If we focus on more of a "wireframe" or "journey" product we can still provide the core useful information of the user experience without the privacy issues of actual recording
- [ ] 🤩😩 **Automation PoC**: Based on our [RFC](https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2023-04-11-automation-v1.md) have a working product (for our team) to power some common use cases. Importantly inform us whether this is feasible, usable and cost effective. 
- [ ] 😒 **Productise in-app bug/feedback reporting**: We use our own in app "bug report modal" _a lot_ and it has improved our support flows hugely. We could wrap this all up and offer it to customers in some form.

## Really side quests...
- [x] Pre-signed Replay URLs (short term sharing of replays via the API)
- [ ] E2E test replays
- [ ] Watch Replays in VSCode
- [x] surface the notebooks activity logs in the UI

# Roadmap

### 📘 [Notebooks V1](https://github.com/PostHog/posthog/issues/15680)

[(Dedicated issues)](https://github.com/PostHog/posthog/issues/15680)

**Comment by pauldambra** [comment]
now firmly in the past
