### ISSUE TITLE
Team Replay Q4 2023 Mega Issue 🤘

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#17803]
# Team Replay Q4 2024 Megaissue 🤘

Previously on the Megaissue: 
* https://github.com/PostHog/posthog/issues/16287
* https://github.com/PostHog/product-internal/issues/456 
* https://github.com/PostHog/posthog/issues/13393 
* https://github.com/PostHog/product-internal/issues/354

This is designed to be a focus point to link together what we plan to do, feedback on that plan and progress as we go forward.

It is **not** meant to be discussion about individual features. As soon as the discussion starts a dedicated feature issue should be created, added to the roadmap and discussed there.

# Goals

# 🎯 Goal 1 : Project "NoteForce Exploration 3000" (Ben, David)

Why? Pairing up with Michael and Thomas from Team Product Analytics to focus on not just releasing Notebooks, but integrating them seamlessly with PostHog 3000 to make it a great experience to explore any and all data across PostHog.

# 🎯 Goal 2 : Mobile Session Replay

Why? - The people want it and we have the right skills in house to do a good job of this. Replay is the main focus, but making mobile a first-class citizen of PostHog is the real goal.

## Why no recordings goal?

With David and Ben focussed on Goal 1 and Manoel focussed on Goal 2 that leaves Paul a team of 1. We're also aware that blob ingestion is still an unknown support load. So staying with two goals lets Paul focus on supporting Manoel and chewing through side quests.

# Offsite SWOT

At Bologna we discussed what we would work on in a perfect world and then ranked those things by their (rough) impact and effort

![PXL_20231017_094542727-EDIT](https://github.com/PostHog/posthog/assets/984817/642f50d9-40f3-4c17-8406-7a3d228bbcf3)

- [ ] 🤳  [**Network request and response capture**](https://github.com/PostHog/posthog/issues/16410)
- [ ] 🔍 **Replay filtering improvement**: It should be easy and intuitive to find the most important recordings. E.g. Search by network error. Search history, search prompts
- [ ] 🤔 **Heatmaps 3000**: Currently we actually have click maps - partly we should make this clearer and more performant, also we could extend the feature using Replay data to have an actual heatmaps.
- [ ] 💸 **Cost control**: we want this product to be fit for everyone and nobody should ever have to leave because it costs to much to run
- [ ] 🎥 **real-time playback**. If you're watching a live recording we should poll for new data so someone can stay watching an important recording (almost) as it comes in
- [ ] 📱 **Mobile dashboard template**: We're going to improve the mobile SDKs, let's make it easy for you to get great insights from the data
- [ ] 📱 **Mobile auto-instrumentation**: We're going to improve the mobile SDKs, let's improve the data we gather automatically
- [x] 😍 **Toolbar 3000**: [UX redesign](https://www.figma.com/file/uNuL5XDnOqasYuK0yfpnmV/PostHog-3000?type=design&node-id=1992-63659&mode=design&t=sXEeEuh89rVrLvI9-0) to fit with the app 3000 work. *AND THEN* make the toolbar an amazing heads-up display bringing your PostHog data into your site
- [ ] 🔨 **Action-based sessions**: Customers typically view replays for a particular flow. We should make it easy to start / stop sessions based on events so that the recordings are not time bound but event bound.

## Really side quests...
- [ ] 🛜 Web Performance 3001: now we capture this information for recordings can we expose it anywhere else? In insights, in a lighthouse view?
- [x] E2E test replays
- [ ] Improved saved playlists (make it easier to get back to your discoveries)
- [ ] Audio in notebooks: you can make text comments, do people want to make audio comments too?
- [ ] ✂️ [Replay Clips - with gif/video exporting](https://github.com/PostHog/posthog/issues/16412)
- [ ] highlight notebook comments on the player timeline
- [ ] query replay data via insights
- [ ] show annotations in the player events list
- [ ] ☢️ Autocapture errors as events: This was deprioritised because of ingestion performance concerns. How can we fix them and ship this?

# Roadmap

**Comment by pauldambra** [comment]
it is no longer q4 2023
