### ISSUE TITLE
Sprint October 30th - November 10th

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#18174]
# Global Sprint Planning

## 3 things that might take us down

1. Clickhouse EU/cloud
2. Terraform - James to schedule an incident analysis

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Project Query Engine

## OKR

- Project "Finish the darned Query Engine" (Tom, Marius)
  - Finish insight HogQL conversion.
  - Support non-event data sources on HogQL insights (BI tools for data warehouse).
  - Build tools to measure HogQL query performance, and catch regressions before they hit users.

## Retro

- Finish the trends & lifecycle insights --> rollover
- Split PoE
  - Split done for HogQL, modifiers available under /debug, not enabled for anyone. 
  - Question regarding rollout and communication.
- Query Planner
  - `/debug` URL where you can manually plan your queries.
  - One automatic "smart" optimisation for persons depending on selected fields.
  - Need to work on a performance suite.

## Planning

- Marius off first week, only Tom working
- Second week Julian's onboarding in Cambridge with the whole team (6 people!)

## High priority

- Trends insights continued (aggregations) @Gilbert09 
- Have a great onboarding week


## Low priority / side quests

- Async slow lane for queries that take 60 < x < 600 seconds to complete.

**Comment by benjackwhite** [comment]
# Team ~Monitoring~ Experience Analytics

**Support hero:** @benjackwhite 

## Retro

- @benjackwhite lots of good stuff in the offsite
- @pauldambra offsite retro issue here https://github.com/PostHog/product-internal/issues/520

## Hang over items from previous sprint

- 🟡 Release Notebooks! @benjackwhite 
  - Thanks to Joe there is at least an issue https://github.com/PostHog/meta/issues/139
  - Mostly polishing from a work perspective
  - Thomas still looking at the remaining insights issue 
- 🟢 Offsite hackathon - release or kill!
  - 🟢 Paul's stuff is getting released!
  - ❌ In-app Video feedback will not get released but super useful reference for future work
  - 🟡 Person feed canvas work - will get released behind a flag
- 🟢 iOS rewrite @marandaneto 
  - Pending tasks - properties sanitization, reliable upgrade path

## OKR

📱 Mobile Replay 🟢
- Android SDK rewrite done ✅ 
- iOS rewrite underway ✅  

### High priority
- Get the team rename done @benjackwhite
  - why? We made the decision, lets not linger on it
- First draft of mobile replay specification @pauldambra 
  - why? We need a reference point of what we are building from both record and playback perspective.
- Android recording PoC / spike @marandaneto
  - why? There are a lot of unknowns - best way to answer that is to build something quickly and see what our options are


### Low priority / side quests
- Network response payloads (work on top of or off of https://github.com/rrweb-io/rrweb/pull/1105)
- Notebooks release follow up

**Comment by robbie-c** [comment]
# Team Web Analytics

**Support hero:** n/a

## Hang over items from previous sprint
n/a

## OKR
🟢 Build the dashboards to match 80% of functionality - work underway and making good progress
⚪ Start working towards the architecture to scale to a general release - not started

### High priority
* Add caching back to the web analytics queries
* Improve UI for filters and restrict which filters can be chosen
* UI tweaks to included trends
* Start adding friendly companies to the closed alpha (first one today!)

### Low priority
* Everything else here https://github.com/PostHog/posthog/issues/18177

**Comment by fuziontech** [comment]
# Team Data Warehouse

### OKR Q4

### Objective

**PostHog users can effortlessly bring their business data to PostHog and analyze it** 🟢

* **Key Results:**
    * Be able to import data into data warehouse in one click from most popular SaaS tools (X, Y, Z connectors built)
    * 5 happy users/teams who have imported external data
    * Data Warehouse queries are compatible with insights hogQL

**PostHog is moved over to whatever CH infrastructure we will be using for the next 1 year (at least)** 🟡 

* **Key Results:**
    * We are either on new infrastructure for EU that we host or on ClickHouse Cloud
    * Queries for large customers are performing faster
    * We can scale more easily (without James bespoke effort)
 

### Retro

**Product**
- [x] Build and test stripe connector for one click data import/sync
- [x] Work through pricing plan for data import. (Necessary because the costs could runaway if we don't charge from the onset) 

**Infra**
- [ ] Develop ability to feature flag / switch cluster a query is dispatched to based on team
- [x] Further testing 720GiB x 3 cluster after downscaling
- [ ] Move over one team for testing 👀
- [x] Cleanups from CH issues last week

### High priority
**Product**
- [ ] <placeholder>

**Infra**
- [ ] Complete required performance improvements with ClickHouse.cloud
- [ ] Remove EBS volumes on Prod US cluster for cost savings

**Comment by EDsCODE** [comment]
# Team Data Warehouse

### OKR Q4

### Objective

**PostHog users can effortlessly bring their business data to PostHog and analyze it** 🟢

* **Key Results:**
    * Be able to import data into data warehouse in one click from most popular SaaS tools (X, Y, Z connectors built)
    * 5 happy users/teams who have imported external data
    * Data Warehouse queries are compatible with insights hogQL

**PostHog is moved over to whatever CH infrastructure we will be using for the next 1 year (at least)** 🟢

* **Key Results:**
    * We are either on new infrastructure for EU that we host or on ClickHouse Cloud
    * Queries for large customers are performing faster
    * We can scale more easily (without James bespoke effort)
 

### Retro

**Product**
- [x] Build and test stripe connector for one click data import/sync
- [x] Work through pricing plan for data import. (Necessary because the costs could runaway if we don't charge from the onset) 

**Infra**
- [ ] Develop ability to feature flag / switch cluster a query is dispatched to based on team
- [ ] Further testing 720GiB x 3 cluster after downscaling
- [ ] Move over one team for testing 👀
- [ ] Cleanups from CH issues last week

### High priority

**Product**
- [ ] Get the pricing and stripe connector through the door and deployed for beta users. All of it should be implemented by end of week
- [ ] Work through a few more connectors (TBD which ones are important)

**Infra**

**Comment by raquelmsmith** [comment]
# TEAM Growth 🎉 

Support hero: Raquel

## Retro
- [x] Get surveys ready for pricing launch https://github.com/PostHog/billing/pull/366
- [ ] https://github.com/PostHog/billing/pull/370
  - should be out today
- [ ] Fix inability to delete orgs due to foreign key on old billing tables
  - hope to start this this week, but prob not done til next
- [ ] Fix revenue forecasting for quarterly billing
- [x] Keep iterating on onboarding exp until it's good
  - did work here, but still some to do. it's going well!
- _Generally got less done this sprint due to onboarding Bianca!_

## OKR

- ⚪  **Objective 1:** Better understand what leads to revenue
  - Reasoning: We're still a bit fuzzy about what metrics are leading indicators for revenue.
  - KR: A company scorecard with actionable insights that help us understand where to invest
  - KR: An understanding (doc or dashboard) of how people use multiple products
- ⚪ **Objective 2:** Simplify and improve the upgrade process
  - Reasoning: It's currently somewhat confusing and requires too many clicks.
  - KR: Increase the percentage of orgs who upgrade to a paid account
  - KR: Decrease or maintain the number of surprise bills that CS has to refund
  - KR: Automatically subscribe people to the products they use
- ⚪ **Bonus Objective 3:** Continue experimenting with onboarding and activation metrics
  - KR: Product-specific onboarding performs better than the old onboarding flow
  - KR: 2 experiments for Product Analytics & Session Replay activation metrics each

## This sprint
### High priority
- [ ] Fix inability to delete orgs due to foreign key on old billing tables
- [ ] Fix revenue forecasting for quarterly billing
- [ ] Keep iterating on onboarding exp until it's good

### Low priority / side quests

- [ ] Change MRR per product reporting to be calculated based on usage, not invoices

**Comment by timgl** [comment]
# Team Pipeline


**Support hero:** ___

## Retro



- Capture-rs is deployed and capturing traffic for team 2 from PostHog-js @xvello - will slip to next sprint. Ellie is working on routing so we'll deploy next week. Prod distracted me.
- Make replicator use compose webhook and elements_chain @tiina303 - Was on holiday for two days + onboarding, repriortise for later.
- Finish migrations of Bigquery and Postgres, and finish redshift app @tomasfarias
- Run PoE experiment in prod and figure out next steps depending on that @bretthoerner - made progress, ran it on prod, which nearly killed PG. trying to improve perf of existing queries. trying to do less back and forth.

### Low priority / side quests

- PostHog-js to send elements_chain as a strong @tiina303 - next sprint
- Showing users webhook metrics @tiina303 -
- Work with Monitoring team to write mini RFC with shape of payload and failures modes of capture @xvello - Manoel didn't have bandwith this sprint, hopefully next sprint.

## Hang over items from previous sprint



- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red
- keep the lights on
  - green, RDK gave us some issues with handling but in a better place now. 
- Batch exports migrations complete - @tomasfarias
  - green, about to migrate people over on bigquery and postgres
- Webhooks v2 @tiina303
  - New delivery system
    - yellow, nothing shipped but Dave said he had some exp with webhook systems - he could potentially ship this
  - New interface for webhooks and onevent apps
    - green, started working on UI for this

### High priority

- Capture-rs is deployed and capturing traffic for team 2 from PostHog-js @xvello
- Build pipeline UI @tiina303 
- Batch exports - migrate bigquery/postgres/redshift + cancel endpoint @tomasfarias @tkaemming 

### Low priority / side quests

-

**Comment by ellie** [comment]
# Team ___

**Support hero:** ___

## Retro



- 

## Hang over items from previous sprint



- Item 1. prioritised/deprioritise

## OKR

🟢   Continued maintenance of systems
🟢   Controlling costs - lots of savings made, new capture progressing well
🟡   Platform improvements - haven't had much progress here yet, but work beginning now


### Tasks

- nginx unit deployed instead of gunicorn - @frankh 
- pods balanced across AZs - @frankh 
- Improving CI reliability and stability - @danielxnj 
- capture running in prod  + tuning - @ellie

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy  

Days off:
Juraj: 0 day
Neil: 0 day
Li: 1 day

## Retro

1. Surveys QA & polish before launch (https://github.com/PostHog/posthog/issues/17038): @liyiy / @neilkakkar - good enough to pause state
2. Finish survey result visualisation updates & events overview: @jurajmajerik - all done!

## Hang over items from previous sprint


---

## OKRs

1. Get 5 reference customers for surveys
2. Get reference customers for feature flags and experiments

### High priority

Switching focus to feature flags again!

- Feature flag Environments: https://github.com/PostHog/posthog/issues/13160 - @jurajmajerik 
- New feature flag targeting options: Relative dates: https://github.com/PostHog/posthog/issues/17392, by distinct ID: https://github.com/PostHog/posthog/issues/13808 - @neilkakkar 
    - Pairs well with: add flag information on server-side library events -> https://github.com/PostHog/posthog/issues/14270
    - Since all of these will touch all server side libs for local evaluation updates 

- Fix toolbar for flags: https://github.com/PostHog/posthog/issues/17616 https://github.com/PostHog/posthog/issues/18079 https://github.com/PostHog/posthog/issues/15481 - @liyiy 


### Low priority / side quests

Stale feature flags: https://github.com/PostHog/posthog/issues/16497

Potentially do geoip updates when touching other server side SDKs: https://github.com/PostHog/posthog/issues/14351

**Comment by benjackwhite** [comment]
# Project Noteforce3000

## Hang over items from previous sprint

- 🟢 Concrete Roadmap (and a timeline) for "3000" (and a clear idea of what that is)
- 🟢 Clear who is building what, and how to collaborate on it to ensure things get shipped
- 🟢 Hackathon based on these outcomes ([follow up work](https://github.com/PostHog/posthog/issues/18191))

### High priority

We will release the UI refresh "base 3000" in the next 2-3 weeks.

- 🔵 Dark (and tan mode) mode polish  ⭐️ @Twixes 
- 🔵 New Nav/Top Bar (child issue: https://github.com/PostHog/posthog/issues/18090) @Twixes ⭐️
- 🔵 Cohorts -> Persons, Annotations -> Data Management (and adding any missing apps) @daibhin 
- 🔵 Universal Search/Command Palette @thmsobrmlr ⭐️⭐️⭐️
- 🔵 Right Side Panel Notebooks @benjackwhite @daibhin
- 🔵 Right Side Panel Feedback + Activity @benjackwhite @daibhin 
- Revert project homepage to "old" mode @benjackwhite 
- Insight fixes for Notebooks @thmsobrmlr 

### Side quests
- Required work from [this](https://github.com/PostHog/posthog/issues/18191) to release Persons Feed
- Michael is doing c++ stuff :o
