### ISSUE TITLE
Web Analytics Public Beta To-Do List

### ISSUE THREAD

**Issue by robbie-c** [PostHog/posthog#18547]
This is the list of work to be done before Web Analytics can remove the beta tag.

This list is open to change, and I'd love any feedback.

### Must-haves
- [x] Performance good enough for large customers
  - [x] Design session table
  - [x] Write session table backfill script
  - [x] Run session backfill
  - [x] Use hogql to limit date range of session queries
  - [x] Update web analytics queries to use sessions
  - [x] Add session-based filters
  - [x] Sessions table v2 TBD
- [ ] Any architectural changes that break data continuity

- [x] Make decision on whether we want to continue to call it "web analytics"
- [x] Fix async queries (internal thread https://posthog.slack.com/archives/C05LJK1N3CP/p1707844028504349 )

### Should-haves
- [x] Live online users count
- [ ] Make it easier to separate sites - https://github.com/PostHog/posthog/issues/12181
- [ ] Show time of last refresh, rate-limit refreshing
- [ ] Visual regression tests

### Could-haves
- [ ] Add chart showing time of day that users visit (two tabs, one for your TZ, one for user TZ)
- [ ] Set all queries to use the exact same time period
- [ ] Group devices by width/height tuples
- [ ] Add % of total for devices and geography tab
- [x] Add Conversion goals
- [x] Add link to definitions in the docs
- [ ] Help people figure out if they have their internal / test filters set up incorrectly
- [ ] Top clicks for people with autocapture set up
- [x] Solve the technical difficulties prevent us from filtering on channel type
- [ ] Improve UX on mobile devices e.g. https://posthoghelp.zendesk.com/agent/tickets/10625
- [ ] LCP/page load for paths
- [ ] Auto-refresh in background
- [x] Show example session replays
- [ ] New vs returning users

### Won't-haves (possibly will be done in the future)
- Integration with google search console

- Hide incomplete periods from graphs
- Improve the UX around searching for a path
- Add a flag to posthog-js to enable sensible defaults for web analytics
- Use the paths insight, shows which paths are best at converting
- Ad attribution postback
- Pulling in data from ads to measure CAC
- Exporting data (e.g. as CSV)
- Figure out how to make sessions span domains, see https://github.com/PostHog/product-internal/pull/531
- Public dashboards

### Historical
- [x] Add a simpler tab to the sources section which just lists Direct/Organic Search/Paid https://github.com/PostHog/posthog/issues/18713
- [x] Path cleaning rules for web analytics - https://github.com/PostHog/posthog/issues/19237
- [x] Add a status check, which warns if analytics are not configured correctly (e.g. not sending pageleave / pageview)
- [x] Graphs should have a configurable interval
- [x] Graphs should show actual dates, not "day 0"
- [x] Add retention chart
- [x] convert browsers/device type to pie chart possible side-quest: improve the pie chart, see history of this https://github.com/PostHog/posthog/issues/4403 https://github.com/PostHog/posthog/issues/5411 https://github.com/PostHog/posthog/issues/4568 https://github.com/PostHog/posthog/issues?q=is%3Aissue+is%3Aopen+pie+charts
- [x] https://github.com/PostHog/posthog-js/issues/876
- ~~(with help of other teams) create web analytics ingestion pipeline, without persons/PoE, without custom properties, no custom events only pageviews/pageleaves and some conversion goals~~ (converted to non-goal)
- [x] (with help of other teams) Create product page on the website and documentation. Tracking questions here https://docs.google.com/document/d/1FNxjoPO4rloFsDnureNh24fhMjdD8FQXslRaSFvrnb8/edit
- [x] button to refresh, refresh time
- [x] Ability to save/bookmark filters
- [x] Larger / full screen view for tables and graphs
- [x] Make "Top pages" wider, include Time on Page, Average Scroll Depth

### Feedback form feature requests
* Convert to a "real" dashboard
* Be able to open urls
~~* Path cleaning~~
* Sites
* Ability to schedule reports, as you can do with dashboards.
* Ability to add a link to a filtered view to a notebook or dashboard.
* Ability to save a snapshot of the web analytics page as a PDF.
* See user information (e.g. have the visitors count be clickable)
* More time period options, like YOY or MOM
* see the exact(or exactish) location of users pinpointed on a world map., like Shopify Black Friday
* Comparisons of Month over Month of the different categories like UTM source, etc
* See cost of customers in posthog through ad integration
* Add example session replays

Previous issue: https://github.com/PostHog/posthog/issues/18177

**Comment by robbie-c** [comment]
Closing this PR as we're out of beta. Anything unchecked will be prioritised as normal
