### ISSUE TITLE
Command Bar Improvements

### ISSUE THREAD

**Issue by thmsobrmlr** [PostHog/posthog#18552]
## Command Bar Improvements

https://github.com/PostHog/posthog/pull/17864 and https://github.com/PostHog/posthog/pull/18355 bring us a global search and command bar. There are a lot of ways to improve it and this issue tracks 

Please let me know what you like / don't like and any other ideas :) Roughly ordered by perceived importance.

### Todos
- [ ] Implement metrics from https://github.com/PostHog/posthog/pull/17864
   - [x] Instrument existing search https://github.com/PostHog/posthog/pull/17899 / https://app.posthog.com/dashboard/110036
   - [ ] Add PostHog events / use autocapture for new search
  - [ ] Add Prometheus metrics
- [ ] Find a way to announce the shortcut in the app (maybe a hint in the sidebar)
- [ ] Don't debounce the initial search load
- [ ] Fix issues originating from current command palette 
   - [ ] Focus command bar when activating a command
   - [ ] Handle executor bugs e.g. display them in the command k menu (see below item)
   - [ ] Fix bug: refresh page on https://app.posthog.com/notebooks and perform the "create dashboard" flow -> logic not mounted

### Ways/ideas to improve the search
- [ ] "Recently searched..."
- [ ] Implement a facetted search interface for tags, authors, etc
- [ ] Boost things the user has created/viewed/... in the search; generally things that are looked at often
- [ ] Maybe try out trigram (fuzzy) search as an alternative
- [ ] Add a preview like on the website
- [ ] Allow searching entities in ClickHouse (persons/events)
- [ ] Hide tabs for features the team doesn't user e.g. hide actions if the team doesn't have any
- [ ] Add a search headline (highlighting the search term in the results)
- [ ] Perf improvement: Limit the number of returned entries per entity
- [ ] Perf improvement: Add a search vector column / GIN index
- [ ] Allow to customize the search language for better results

### Ways/ideas to improve the commands
- [ ] Add commands to toggle light/dark mode
- [ ] "Recently performed..."
- [ ] Add commands for all product sections
