### ISSUE TITLE
Team Replay Q1 2024 Mega Issue 👨‍🎤 

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#19327]
# Team Replay Q4 2024 Megaissue 🤘

Previously on the Megaissue: 

* https://github.com/PostHog/posthog/issues/17803
* https://github.com/PostHog/posthog/issues/16287
* https://github.com/PostHog/product-internal/issues/456 
* https://github.com/PostHog/posthog/issues/13393 
* https://github.com/PostHog/product-internal/issues/354

This is designed to be a focus point to link together what we plan to do, feedback on that plan and progress as we go forward.

It is **not** meant to be discussion about individual features. As soon as the discussion starts a dedicated feature issue should be created, added to the roadmap and discussed there.

# Goals

### 🎯 Goal 1: 10 Happy Android Replay User 

We'll also release an alpha of iOS Mobile Replay.

Why? 

We've done the work's base and now we want to release the new Android SDK with session replay and onboard customers to validate the product. 

### 🎯 Goal 2: Reduce churn

Why? - Churn is higher than we'd like, this is a signal we're not getting some things right. We're not serving our users as well as we can until we're getting this right.

### 🎯 Goal 3: First-class mobile support in app.posthog.com

Why? We're making the mobile SDKs equivalent to the web SDKs. We want to make sure that the mobile SDKs are first-class citizens in app.posthog.com so that it is easy to use and explore your mobile data.

# Planning

We got together in London before the xmas party and talked about what is going well or not with the team and the product

![image](https://github.com/PostHog/posthog/assets/984817/70a76590-0a44-412c-986b-339e786882a8)

and prioritized what we might work on

![image](https://github.com/PostHog/posthog/assets/984817/d5c53943-2c06-483b-859d-74c95ec5ffbb)

![image](https://github.com/PostHog/posthog/assets/984817/292ce001-dd68-4c26-b30c-b8db48adc601)
![image](https://github.com/PostHog/posthog/assets/984817/dc76c9a4-10ab-4a40-8209-45ecf4a656e4)

- [ ] 💸 **Cost control**: we want this product to be fit for everyone and nobody should ever have to leave because it costs too much to run
- [ ] 💸 **Price changes**: we want this product to be fit for everyone and nobody should ever have to leave because it costs too much to run
- [ ] 🤳  [**Network request and response capture**](https://github.com/PostHog/posthog/issues/16410)

- [ ] 🤔 **Heatmaps 3000**: Currently we actually have click maps - partly we should make this clearer and more performant, also we could extend the feature using Replay data to have an actual heatmaps.

- [ ] 🎥 **real-time playback**. If you're watching a live recording we should poll for new data so someone can stay watching an important recording (almost) as it comes in
- [ ] 📱 **Mobile dashboard template**: We're going to improve the mobile SDKs, let's make it easy for you to get great insights from the data
- [ ] 📱 **Mobile auto-instrumentation**: We're going to improve the mobile SDKs, let's improve the data we gather automatically
- [ ] 🧠 **Blobby knowledge transfer**: With Ben leaving the team we need to spread the knowledge out of Paul's head and prepare for sharing this ingestion workload with pipeline
- [ ] 📞 [**Mobile Replay**](https://github.com/PostHog/posthog/issues/19037) 🚢🚢🚢🚢🚢🚢 
- [ ] 🐁 [**Dead clicks**] Can we capture more signals to help users find out what is happening
- [ ] 📜 [**Scoring**] Can we surface more important or interesting recordings automatically to help users find the gold more easily

## Really side quests...

- [ ] 🔨 **Action-based sessions**: Customers typically view replays for a particular flow. We should make it easy to start / stop sessions based on events so that the recordings are not time bound but event bound.
- [ ] 🔍 **Replay filtering improvement**: It should be easy and intuitive to find the most important recordings. E.g. Search by network error. Search history, search prompts
- [ ] 🛜 Web Performance 3001: now we capture this information for recordings can we expose it anywhere else? In insights, in a lighthouse view?
- [ ] Improved saved playlists (make it easier to get back to your discoveries)
- [ ] Audio in notebooks: you can make text comments, do people want to make audio comments too?
- [ ] ✂️ [Replay Clips - with gif/video exporting](https://github.com/PostHog/posthog/issues/16412)
- [ ] highlight notebook comments on the player timeline
- [ ] query replay data via insights
- [ ] show annotations in the player events list
- [ ] ☢️ Autocapture errors as events: This was deprioritised because of ingestion performance concerns. How can we fix them and ship this?

# Roadmap

**Comment by annikaschmid** [comment]
@pauldambra I found this a bit hard to read, because you put the goals at the bottom, and then the tasks to achieve the goals further down the page. For readability, this is how I would structure it

Goal
Why
- Task 1
- Task 2
- Task 3

Side quests
- Task 1
- etc

Real side quests
- Task 1
- etc

Pictures from workshop at the bottom, for those who are *really* interested

**Comment by pauldambra** [comment]
Cool - I shifted things around @annikaschmid. Feel free to edit directly in future 😊

**Comment by rcmarron** [comment]
Hello! Happy Holidays! Just chiming to say I'm really excited to see canvas recordings on the list here! It'd be huge for my use case! (It's a web-app where graphs are displayed using canvas elements). Seeing the graphs that the customer is seeing is huge for understanding how they're using the product and what they're discovering with it. Without it, I end up needing to login and recreate what they're doing to understand what's happening. Happy to be a beta tester or chat more about my use case if it's helpful!

(Also, love seeing all the progress on recordings! Keep it up!)

**Comment by daibhin** [comment]
@rcmarron we're just about ready to test canvas recording to gather some feedback! If you (or anyone else reading this who might also be interested) wants to shoot me an email on david@posthog.com I'll happily get you setup

**Comment by marandaneto** [comment]
@pauldambra 

> Cost control: we want this product to be fit for everyone and nobody should ever have to leave because it costs too much to run

This should have been checked right? it was not available for all plans but the feature itself was done.

**Comment by pauldambra** [comment]
Yeah, I didn't check because it wasn't completely out... but I think safe to say it's out now (certainly the last bits aren't going to be forgotten :))

**Comment by pauldambra** [comment]
time has passed and it's not Q1 any more
