### ISSUE TITLE
Persons on Events

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#20460]
Related: https://github.com/PostHog/meta/issues/173

The primary goal of this issue is that PoE query mode (in terms of unique users) will return exactly the same results as joins with the person & distinct_id tables

## To Do
- [x] Update squash workflow to utilize distinct ID overrides: #20329
- [x] Implement backfill: #20562, #20886
- [x] HogQL Support: #21059
- [ ] Feature flag for opting queries into v3 query path: #21150

### Improvements
- [ ] Evaluate benefit of using a dictionary for override lookup: #20971
- [ ] Improve handling of deleted events when using overrides https://github.com/PostHog/posthog/pull/21059#issuecomment-2010696234
- [ ] Fix distinct_id reuse (possibly by tombstoning PG records) #20187

### Clean Up
- [ ] Remove unused person overrides code and models/tables
- [ ] Revert #20659 to optimize squashes
- [ ] Additional considerations for self-hosted (backfilling, …)
