### ISSUE TITLE
Remaining work for Mr Blobby v3 rollout

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#20580]
## TODO
- [ ] Release it in test mode on US as well
- [ ] Let it run for a few days (ideally into some sort of tricky scale situation to see how it reacts)
- [ ] Evaluate the additional costs due to EFS
- [ ] Add back in autoscaling so we can see the cost benefits (as rebalancing is less of a big deal)
- [ ] Validate that loading real time an s3 data works as it should.
- [ ] Come up with clear plan to swap over (should be somewhat straightforward)
  - [ ] Needs to add back in the replay and console log ingesters safely

## Unrelated follow up
* Test the S3 tiered storage by reverting offsets to a much older point and seeing how it goes (see [this thread](https://posthog.slack.com/archives/C0374DA782U/p1709024648940839))

**Comment by pauldambra** [comment]
no blobby on efs 💸
