### ISSUE TITLE
Materialization job improvements epic

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#21213]
## Bug description

Materializing column is by far the best optimization we have to speed up queries (even better than PoE), but we've had to disable the current materialization job as it would cause incidents on monday morning. We need to do a couple of things to fix it:

- [ ] Make the backfill query more specific, ie only backfill the columns for the teams that showed up in the analysis query (by adding a `where team_id IN ()` predicate)
- [ ] Figure out why the backfill query hits partitions outside of the ones that 
- [ ] Probably look at the timing of when we run it so it completes before the monday morning increase in traffic

Apart from that, there are some improvements we can make
- [ ] $insertBigCustomer [regularly has cohort calculations fail](https://posthog.slack.com/archives/C04F85S6BGQ/p1711122299212809) because properties aren't materialized on the persons table. We should create a new analysis. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
