### ISSUE TITLE
[EPIC] Great demo environment

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2128]
An accessible, elegant and explanatory demo environment will help us make the case for using PostHog to potential/new users.
There are a few things we can do:

1. [ ] Rework Hogflix's frontend for a more elegant look and code quality.
1. [ ] Enhance the quality of dummy data we have for Hogflix (by increasing quantity).
1. [ ] Allow for checking out PostHog UX with a signup-less "Explore Demo" option, filled with dummy data (akin to [what Amplitude does](https://analytics.amplitude.com/login/try-amplitude) – issue PostHog/posthog-production#18).
1. [ ] Instrument a guided demo flow to showcase PostHog's abilities.

[Relevant designs by @paolodamico on Figma.](https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PH-Retention-optimisations?node-id=304%3A11)
