### ISSUE TITLE
Data Warehouse Public Beta Checklist

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#22001]
### Feature request

Right now Data Warehouse is in opt-in beta. This isn't an effective way to test more widely

**Goal:**
Prepare the feature for public beta—users don't need to opt-in. The feature set will just be available but still tagged as beta

UI (within scope of team):
- [ ] Confirm when/if data pipeline 3000 is getting deployed
- [ ] Decide on and implement: Move data source import settings into data pipeline 3000
- [ ] Implement: Add data table tree view/toggle to SQL pane
- [ ] Decide on and implement: Move data warehouse scene pages into data management. (This might make discoverability really bad)
- [ ] Onboarding/growth prompts are correct

UI (figure out what rest of the teams are thinking):
- [ ] SQL Editor should have it's on sidebar menu

Pipeline:
- [ ] Observability: Quick links for logs to diagnose issues per team/per workflow
- [ ] Observability: Overview of worker capacity and running jobs. Will need to figure out if we need to scale up workers or not

Insight filtering:
- [ ] QA person property filtering from linked sources worked
- [ ] QA basic graphing of data warehouse tables works

Docs:
- [ ] "Under the hood" says we dont import data. people confuse this with meaning that none of the external data syncs import data
- [ ] Add zendesk section
