### ISSUE TITLE
Rewrite replay filtering as HogQL filters

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#22054]
in order of increasing exciteability

- [x] Ensure date clamps on joined tables in hoqgl
- [x] Port each filter directly to hogql
    - [x] Person properties
    - [x] ~~(Any top level property)~~ we don't have the UI to do _any_ property so that's not a direct port 
    - [x] Events (with filters)
        - [x] Some timestamp clamping needs fixing
    - [x] Actions (with filters)
    - [x] Cohorts
    - [x] Group properties?
    - [x] Console log text
    - [x] Console log level
    - [x] Time
    - [x] Duration
    - [x] Internal/test account filters
    - [x] Ordering
    - [x] Paging
        - [x] Looks like there’s an existing paginator class we can re-use
- [x] Measure performance with flag on and off in prod
- [x] session properties support
- [x] Look at whether we can steal insight filter UI directly (ish) once we’ve got hogql running
- [ ] can we use the same query generator for the events subquery as the activity page?
- [ ] Screenshot or e2e tests of this UI
- [x] Put session replay thingies in taxonomic filter
- [x] Put magic filters as a front page of the taxonomic filter

**Comment by pauldambra** [comment]
see zendesk https://posthoghelp.zendesk.com/agent/tickets/13257 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15304) which looks like a bug (pre-hogql) filtering recordings by an action that filters on "all events"

**Comment by daibhin** [comment]
As part of this work we should make Replay filters much more powerful, ideas include:
- And / Or filtering groups
- Multiple duration filters (e.g. > 10s, and < 1h)
- Unified console log filters

### Tasks
- [ ] Add "event occurred" filter to `PropertyFilters` https://github.com/PostHog/posthog/pull/22592
- [ ] Add "console log" filter to `PropertyFilters`
- [ ] Add `Replay` tab to `TaxonomicFilter`
- [ ] Allow 1 level of filter group nesting
