### ISSUE TITLE
EPIC: Retention

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2228]
We have quite a few issues related to retention that I think it's best to have an EPIC to discuss the overall direction of the feature.

### Improvements & new features
- [x] Cohortizing events / first-time retention: #2219
- [ ] Rolling/unbounded retention: #2220
- [x] Cohorts graph: #1936
- [ ] Rolling timeframe: #2227
- [x] UX improvements: #1995, #1643
- [x] Multiple retention events: #1344
- [x] Cohort double clicking / User list: #2562
- [ ] Timeframe selector: #2831
- [ ] Extend timeframe horizon: #2832
- [x]  Show period in progress in retention table: #2833

### Bug fixes
- [ ] Filtering bug: #2654 
- [ ] Persons double clicking issue on CH: #2794
- [x] Period composition bug: #2795
- [x] Retention queries not saved correctly on dashboard: #2817

**Comment by paolodamico** [comment]
Worth mentioning another retention idea here: #2828

**Comment by paolodamico** [comment]
Another thing worth mentioning (not really sure it's quite worthy of its own issue yet) is that opening the persons table takes a loong time (even with a small number of users).
