### ISSUE TITLE
Data Warehouse Pricing Release Checklist

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#22669]
- [ ] can choose to sync incrementally
- [ ] billing system is fully integrated. Teams can set their rows synced limits
- [ ] Pausing/disable a job without deleting the data
