### ISSUE TITLE
Sprint - June 10 to June 21, 2024

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog#22702]
### Feature request

# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by marandaneto** [comment]
# Team A nightmare on CSS parsing street

**Support hero:** @pauldambra  

* manoel (10th) and paul out a day

## items from previous sprint

### High priority

- hiring (@pauldambra) 🟡
- hogql filters performance (@pauldambra ) - :white_check_mark: (check with marius)
    - intercept person property queries and convert them to subquery not join (housewatch thinks 14x faster)
    - can't roll out as is
- users like the screenshot option for android - so add it to iOS (@marandaneto) 🟡
    - should have a draft PR either today or tomorrow for review
- continuing CSS issues as most important customer problem (@daibhin) :white_check_mark:
    - CSS fix but there are some issues capturing mutations

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red

- 🟡 quality and consolidation
    - mobile replay open beta
        - out free and being promoted in onboarding
    - replay captures every site
        - David working with rrweb to improve CSS parsing, already a major reduction in issues as a result
    - people can find the valuable recordings 
        - queued behind the others
- 🟡 Error tracking MVP
    - need to decide if we start
- 🟡 Hire _at least_ 2 amazing colleagues
   
### High priority

- hiring (@pauldambra)
- screenshots blurring (PII) for Android and iOS @marandaneto
- Error tracking (@pauldambra and @daibhin)

### Low priority / side quests

- mobile usage report stuff @pauldambra 
 - persistent replay queue in posthog-js @pauldambra 
 - icons left/right for android wireframes @daibhin 
 - we are recruiting beta testers for Android and iOS - (we should have screenshots now) @marandaneto @annikaschmid

**Comment by benjackwhite** [comment]
# Team ~CDP~ HogHooks

(Now @mariusandra and @benjackwhite )

## Retro

- Focus issues at first, got resolved
- Ben and Marius figured out how to split work effectively (Ben plumbing, Marius compiling)
- Got a MVP up in a few days which felt great

## Hang over items from previous sprint

N/A

## OKR

1. Get the new CDP in front of real users

## Sprint plan

- [ ] Have the new "CDP" service in production, flagged to Team 2 @benjackwhite 
- [ ] Get all of our existing Zapier actions (e.g. slack notifications) running as hog functions (dog-fooding) @benjackwhite
- [ ] Missing hog features to support the above ([related issue](https://github.com/PostHog/meta/issues/208)) @mariusandra

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @jurajmajerik then @Phanatic      
Days off:
Juraj:   days
Phani: 0 days
Dylan: 0 days
Neil: 1 days

## Retro


- Finish up repeated surveys - @Phanatic 
- next start on Event based triggers for surveys - https://github.com/PostHog/product-internal/pull/556 - @Phanatic 
- https://github.com/PostHog/posthog/issues/18102 - @dmarticus 
- NPS survey result fix (ex: [this survey](https://us.posthog.com/project/2/surveys/018b6615-0d7a-0000-bbbc-1ab59bce6866) ) - @dmarticus 
- Surveys popup refactor - @jurajmajerik 
- https://github.com/PostHog/posthog/issues/22131 continue on rewrite - @neilkakkar 

## Hang over items from previous sprint

---

## OKRs

1. Make sure feature flags can handle 10x current scale
2. Polish new experiments UI & collect feedback
3. Add most requested surveys functionality

### High priority



### Low priority / side quests / maybe Neil will get to this next year

- Temporal queues for feature success - @neilkakkar 
- Setup instrumentation for flip-flopping problem of experiment significance - @neilkakkar

**Comment by EDsCODE** [comment]
# Team Data Shack

### OKR Q2 2024

### Objective

**Release data warehouse to everyone**

* **Key Results:**
    * Integration first experience
         * schemas are reliable
         * modeling of each integration is clear
         * Good automatic roll up views and joins
         * Wizard to onboard people
    * Establish a solid pattern to build integrations
    * Complete data warehouse experience in the rest of the app (insights, feature flags, experiments)

**James as a Service -> Clickhouse as a Service**

* **Key Results:**
    * Better Visibility
         * Regularly testing backups
         * Monitoring/alerting
         * Mutations
         * Moves
    * Management
         * Managing/killing mutations
    * Self Serve
         * Schema design feedback (James non blocking
         * Schema management   
    * Automation
         * Replace/Upgrade replicas
         * Upgrading to 24.04
         * Disk configs 
 
### Retro


**Product**
- [x] complete https://github.com/PostHog/posthog/issues/22001 (decide on pricing, UI changes, instrumentation) @EDsCODE 
- [x] Warehouse props in breakdown filters @Gilbert09 
- [ ] warehouse props in feature flags and experiments

**Infra**
- move to team clickhouse!

### High Priority

- [ ] incremental syncs @Gilbert09 
- [ ] templated joins @EDsCODE 
- [ ] warehouse props in feature flags and experiments

**Comment by frankh** [comment]
# Team Infra

## Hang over items from previous sprint

1. 🔴 Investigate canary deploy rollback improvements @frankh 
    - reworking how deploys are done in general to simplify rolling back before working on canary specific rollbacks/locks
2.  🟢 metabase pro set up
    - do we actually need pro? We can set up google sign on with free edition @benjackwhite 

## OKR

1. 💪 Deploy with confidence 🟢 
- Finalize our Canary Deploy process 🟡
5. 🚨 Improved alerting and monitoring 🟢 
- SIEM work has made this a priority
6. 🔒 Deeper Security 🟡 
9. 💰 Continued cost control 🟢 

### High priority
- SEIM: 
     - access logs to django @benjackwhite (fix axes?)
     - cloudtrail dashboard @danielxnj 
     - eks audit dashboard @danielxnj 
     - documentation/policy for sharing with auditors/clients (in cloud-infra?) @danielxnj 
     - metabase logs into loki
- secrets
    - vault monitoring+backups @danielxnj 
    - CDP integration @ZeleniJure 
- placeholder cost optimisation tasks @frankh (to be decided in cost optimisation meeting)
- roll out new codified deployment strategy @frankh 
- internal RBAC review (tbc)

**Comment by fuziontech** [comment]
# Team Click Haus

### OKR Q2 2024

### Objective

**James as a Service -> Clickhouse as a Service**

* **Key Results:**
    * Better Visibility
         * Regularly testing backups
         * Monitoring/alerting
         * Mutations
         * Moves
    * Management
         * Managing/killing mutations
    * Self Serve
         * Schema design feedback (James non blocking
         * Schema management   
    * Automation
         * Replace/Upgrade replicas
         * Upgrading to 24.04
         * Disk configs 
 
### Retro

**Infra**
- [x] 🗑️ Fix delete code path
- [x] ⬆️ Upgrade EU CH version **Must complete**
- [x] 🏗️ Rebuild very broken EU coordinator
- [x] 🗒️ Develop long-term plan for CH strategy
- [x] 🔥  Fire-fighting replication issues in EU w/ `sharded_sessions`
- [ ] ⏩ Move parts around so last 3 months of data are on NVME on US


### High priority

**Infra**
- [ ] ✍️ Write up the outcome from CH strategy planning
- [ ] 🏃 Onboarding plan for Dani
- [ ] 📟 Monitoring and Alerting on EU Coordinator
- [ ] 🧪 Test incremental backup restores
- [ ] ♻️ Replace offline nodes w/ nvme nodes

**Comment by raquelmsmith** [comment]
# Team Growth

## Retro
<details>
<summary>Retro items</summary>

### High priority
- @raquelmsmith 
    - [x] UI for personless events
        - [x] App billing page
        - [x] App pricing tables
        - [x] Onboarding instructions
        - [x] posthog.com pricing tables
    - [x] Launch personless events / project management
    - [ ] Referrals: add/edit referrer and redeemer
- @xrdt 
    - [x] Deprecate available_features
    - [x] Support multiple org owners 
        - Can only invite at your perm level or lower
        -  Can set membership level when inviting
    - [x] Billing admin improvements - make plans_map a dropdown of selects
    - [x] Doc for how to use multiple stripe customers to a single django admin customer
        - Not standalone doc
    - [ ] Maintenance
	    - [x] Track celery queue depth for billing workers 
    	- [x] Check whether billing limits are being applied correctly - see https://posthog.slack.com/archives/C043VJ93L3B/p1715964424235799
    	- [x] Check whether mrr is being forecasted correctly for upcoming invoices
	    	- [ ] ~Add a field to the DB model for the current accumulated total so we can more easily debug future issues~
- @zlwaterfield 
	- [x] 	Finish teams addon changes
		- remove old teams plan
		- make sure enterprise customers are on proper plans
		- Add `includes` team plan to enterprise plan in default config
	- [x] 	Finish startup plan analysis
		- how many credits are being used each month
		- fix the starting/ending balance bug
	 - [x] Stripe audit stuff
 		- mismatch subscriptions script
	 	- emailing users for failed payments
	- [x] Start subscribing to all products
	- Side quests:
        - [ ] Teams annual plan
</details>


## Q2 Goals
✅=finished 🟡=in progress 🔴=won't finish
1.  ⚪ Create a flow in product analytics onboarding to fill out a dashboard template using actions (Raquel)
2. 🟡 Simplify our subscription flows (Zach, supported by Raquel)
3. 🟡 Launch pricing changes (Bianca, Raquel)
    - 🟡 Personless events - will help us reach more customers at an affordable price
    - Data warehouse - it's becoming pretty useful, we should charge for it
    - Session replay - we can reduce costs to improve retention and reach more people

## This sprint

- @raquelmsmith 
    - [ ] Finish roll-out of personless events
        - Update migrate script to also report usage at time of migration
        - Roll out to 5-10k customers at a time 
        - Fix changelog link
        - Fix sentry errors
    - [ ] Referrals: add/edit referrer and redeemer
    - [ ] Start working on toolbar dashboard template thing
    - [x] Prune usage report queries
- @zlwaterfield 
	- [x] clean up outstanding feature flags (reverse-proxy-onboarding and email-verification-ticket-submission)
	- [ ] ship outstanding PRs (Teams addon - remove modal, Projects pay gate on free should be to paid not teams)
	- [ ] subscribe to all products
		- main API changes (basic serializer set up, products=all query, default paid/free plan map, functions for upgrading/downgrading
		- feature flag in UI on billing page with main button alterations (no comparison or other UI changes)
	- [x] startup plan metadata RFC
	- [x] emails new Teams addon customers
	- [ ] re-run the plans map and compare with the new auto-cancel functionality 
* @xrdt 
  * [ ] Billing api performance improvements
  * [ ] Data warehouse pricing?
  * [ ] Making sync invoices reactive
  * [ ] Billing limits in onboarding
  * [ ] Billing breakdown improvements
    * [ ] Show autocapture events 
    * [ ] Show per-project usage breakdowns

**Comment by tiina303** [comment]
# Team Pipeline

Off: Brett 4 days
Support: Brett

## Retro

### High priority

- [x] Kafka migration (Brett)
- [x] Capture-rs successfully processing all /batch requests on EU (Xavier)
- [ ] Changing what data pipeline add-on covers (Tiina)
     - not done, tbd what the new CDP team wants to do
- [x] Fast configuration option to send events to overflow from capture for replay events (Tomas)
- [x] Fixing partition stats (Ted)

## OKR

✅=finished 🟢=on track to finish this quarter 🟡=might not finish 🔴=won't finish
✔️=progressed last sprint ; ➡️=planned work for this sprint

🟢✔️ Deprecate posthog-events by moving to capture-rs fully (21659)
🟢✔️ Visibility into what's in the ingestion queues and past performance (20985)
🟢✔️ Fast configuration options to speed up incident recovery, e.g. by token send to overflow or drop (21662)
🟢➡️ Iterate on person processing to make it faster and cheaper (21048)
🟢✔️ Batch exports UX improvements, e.g. error notifications and UI rewamp (21139)
_  Person data batch export (20339)
   -> moving to Data Warehouse team
🟢➡️ Support adding new products (21665)
🟢✔️ Deprecate scheduler & jobs deployments, runEveryX plugins and kafkajs consumers (21656)

### High priority

- [ ] Improve ingestion efficiency by moving the last Kafka waits at the end of the batch (Brett)
- [ ] New customers [write to person only from `$set` and `$identify`, `$create_alias`, `$merge_dangerously`](https://github.com/PostHog/posthog/issues/22720) and new products also only read persons (Tiina)
    
### Low priority / side quests

- [ ]

**Comment by robbie-c** [comment]
# Team Bounce Rate

**Support hero:** @robbie-c 

## Retro

Had 5 days off this sprint, support was quite busy. Have passed on some issues to relevant teams (sorry product analytics)

- 🟢 test left join changes on persons table (sort of, we could test this more)
- 🟢 run personless upgrading test
- 🟡 write the SQL for the new sessions table that uses it

Torn between 2 things a bit:
* there's a pretty bad bug with the sessions table on EU, somehow during ingestion events are double count (not in events table, only in sessions table which uses a clickhouse materialized view). This means that all bounce rate calculations are 0%. We already wanted to replace this and I've been working on a new design, so could prioritise this
* there's also still a lot left to do on personless events

## OKR

1. Make querying fast enough for large customers
2. Do personless events work where necessary
3. Iterate on customer feedback
4. Product management work

### High priority
- Start emailing a ton of customers for research
- Posthog-js: Rewrite posthog-js person props backfilling to include initial current url
- Posthog-js: handle setPersonPropertiesForFlags properly when personless
- Posthog-js: handle manually calling $set properly when personless
- Write RFC for client changes for personless events based on posthog-js, to be approved by mobile sdk teams
