### ISSUE TITLE
pipeline 🤝 replay ingestion changes

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#23395]
### Feature request

pipeline and replay teams are going to trade time to improve heatmap_data and $exception event ingestion

## why change heatmap data ingestion? 

we get many heatmap_data items per event that carries them, so if we're under heavy load we automatically take a multiple of that load and it's hard to scale/react because the magnification is happening inside main event processing

### TODO

- [ ] move heatmap_data from being a passenger on other events to on its own $$heatmap_data event @pauldambra 
- [ ] flush heatmap events on a timer in posthog-js @pauldambra 
- [ ] update ingestion runner to make sure heatmap data keeps flowing (if necessary) @pauldambra 
- [ ] update django capture so that it can be configured which kafka topic $$heatmap_data events are written to (so that we can switch to...) @pauldambra 
- [ ] update capture-rs so that it can be configured which kafka topic $$heatmap_data events are written to (so that we can switch to...) 
- [ ] add a new plugin-server ingestion deployment that handles $$heatmap_data events and only does validation and writing to the heatmap ingestion topic (it can do no other processing no $set, no exports etc ( heatmaps are free so we'll keep processing cheap)
- [ ] investigate writing one message to CH kafka topic which is exploded in the materialized view that ingests them instead of sending one kafka message per heatmap data item @pauldambra ??

## why change $exception data ingestion

we want to add more processing to these events, that will require changes to speed of processing, infra requirements, etc, we want to make these changes without breaking main event ingestion

### TODO

- [ ] setup `/i/v0/x` ingestion route
- [ ] make sure any $exception event can be configured to be sent to the new route @pauldambra 
- [ ] duplicate capture for that route or change capture so that it writes to a different new ingestion topic (not sure which is best)
- [ ] add a new plugin-server ingestion deployment that reads from the new topic and does the same processing as today but will only receive $exception events (it'll be this deployment that we can then experiment with separately)

**Comment by pauldambra** [comment]
@tiina303 dumped my thoughts here since we've probably gone beyond slack

i'd be happy to discover i'm wrong so feel free to say what tasks i'm missing / or can delete / or shouldn't be trying to do etc etc
