### ISSUE TITLE
meta: insight view issues

### ISSUE THREAD

**Issue by aspicer** [PostHog/posthog#24869]
## Bug description

A meta ticket for tracking insight view issues, if somebody is working on that area:

- [ ] https://github.com/PostHog/posthog/issues/24868

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```
