### ISSUE TITLE
Epic: Editor & Modeling 3000

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#26193]
Goal: We're undergoing a rebuild of our data warehouse/sql editor scene to improve UX and become a full fledged and joy-sparking editor.

**MVP - this will be sufficient as a replacement for the existing editor**
- [x] new layout that full screens the editor with resizable panels (https://github.com/PostHog/posthog/pull/25686)
- [x] multi tab support (https://github.com/PostHog/posthog/pull/25686)
- [x] virtualized result table component (https://github.com/PostHog/posthog/pull/25686)
- [ ] integrate nav 3000 sidebar with sources, tables, views (https://github.com/PostHog/posthog/pull/26184)
- [ ] sidebar is searchable (https://github.com/PostHog/posthog/pull/26184)
- [ ] refactor logic for multitab editor (https://github.com/PostHog/posthog/pull/26128)
- [ ] click on a schema and see the fields in sidebar
- [ ] sidebar sources section should link to source configuration
- [ ] Add visualization tools to result pane as a new tab
- [ ] Editable tab naming
- [ ] Improvement: Export results view as CSV
- [ ] Improvement: Save views without aliasing

**Upcoming:**
- [ ] Guidance around special syntax (links in tables)
- [ ] Draft query edits
- [ ] Reorganize sidebar to enable drafts/views/tables
- [ ] Joins: list of fields is disorganized and unintuitive
- [ ] Canvas view of table relationships (another tab alongside results/visualizations)
- [ ] Remove the editor from insights page

**Further out:**
- [ ] SQL autocomplete
- [ ] Model run scheduler

**Comment by annaszell** [comment]
Some of my wishlist items:
- debugging --> I am prone to make silly mistakes (forgetting a comma, a parenthesis, etc.), so if the error message could tell me or maybe even highlight the row where the issue is, that would be simply lovely. I know we have the red underlining but it doesn't always work properly. iirc Databricks highlights the part of your code in red that results in it not running (I haven't used Databricks in over a year now though so not 100% sure)
- formatting --> I'm terrible at being consistent when I write my queries, so before I share it for review with someone, I usually copy-paste it to ChatGPT to format it for me, so people have an easier time understanding what's going on
- clearer indication that by default only the first 100 rows will be shown (e.g. when I open a new tab, the example query has the LIMIT 100 but if I remove that and rerun it, it's still 100 results), and how can I override this
- partial runs --> so especially when I'm investigating something, it would be helpful to just run parts of the query within the same tab by using `;` at the end of each query instead of commenting things out. sometimes I forget the exact fields/properties and I just want to have a quick look at the schema, etc. e.g. below 👇  and I could just highlight the one I want to run, it works like this in Metabase (and others)
> select 
> 	id,
> 	country,
> 	event
> from events;
> 
> select * from events limit 1;
this is not a super annoying thing but it would be helpful in certain scenarios
- time outs --> this one is a minor issue but I'd love it if a query that would eventually time out wouldn't even run, just tell me it's not gonna happen so I don't sit there for minutes. I know it's a first world problem, hence being the last one
