### ISSUE TITLE
[EPIC] Funnels

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2697]
Improving our funnels functionality to truly reach feature parity with other product analytics tools. Original issue that sparked this was #2642. 

### Some Suggestions

- [ ] Conversion between steps built-in (not by hacking around it with separate funnels)
- [ ] Line graph of conversion over time (#1269)
- [ ] Funnel breakdowns: might require us to change our funnel design?
- [x] Funnel Step Reordering (which we never merged #1245)
- [ ] Step ordering options:
     - `exact order` (A -> B with nothing in between) 
     - `this order` (A -> B or A -> C -> B)
     - `any order` (B -> A or A -> B or B -> C -> A)
- [ ] Exclusion steps: user did A -> B without having done C in between
- [ ] Fine-tuning conversion criteria: "converted within", "holding property constant"
- [ ] Segmenting steps (#3601)

@EDsCODE

**Comment by paolodamico** [comment]
Relevant [customer feedback](https://docs.google.com/document/d/1gJlsUDrlW7ur8zT5scqRvXZhapm_0JdvKGiw68Iyx9E/edit#heading=h.m0t14azci1oz)

> We have a funnel about our main flow. However, it’s not very useful, hard to see changes over time. Not that actionable.

**Comment by paolodamico** [comment]
In anticipation that this is something the core analytics team might work on during the next sprint, here are some initial wireframes ready for feedback (@EDsCODE @buwilliams). These wireframes support introducing all the functionality covered in this issue. Even if we implement this progressively, having context on the entire UX should be helpful.

I'm planning to work on HiFi mockups on Wed, depending on the feedback received here. Part of this, @corywatilo it'd be incredibly helpful if you could help me rethink the UI of the actual funnel graph as we work on improving this too (see [relevant thread](https://posthog.slack.com/archives/C01G8S5T08Z/p1622207198088500)).

## Funnels Option A
- Verbose filters. Useful for discovery and new users.
- Note we've moved to the horizontal layout too for consistency.
<img width="800" alt="" src="https://user-images.githubusercontent.com/5864173/120222253-7f7cd300-c1f4-11eb-9cec-0a6f65a593cb.png">

## Funnels Option B
- Grouped filters. Cleaner for returning users.
<img width="801" alt="" src="https://user-images.githubusercontent.com/5864173/120222246-7c81e280-c1f4-11eb-8034-d5997163f85d.png">


## Conversion over time
<img width="799" alt="" src="https://user-images.githubusercontent.com/5864173/120222232-7855c500-c1f4-11eb-8746-6f7f03aae689.png">

**Comment by paolodamico** [comment]
Closing in favor of #4785
