### ISSUE TITLE
[EPIC] Insight improvements

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#2877]
A list of low hanging fruit (+ a few bigger tasks) that would make the insight experience more complete. I've associated some of the bugs. Feel free to add more

General:
- [ ] saved funnels should have consistent analogies across the other insights
- [x] generally it’s not immediately clear you can click to see people
- [ ] should be able to cohortize users really easily anytime you see a group of people (ex: clicking on a datapoint)
- [x] #2932  manual cohort building where you can create a cohort from a group of emails you list #2868 
- [ ] When you go from dashboard to an insight, and you then select a different insight (going from trends to retention for example) it still shows 'update dashboard' from that previous insight. We might need to have the concept of 'creating a new chart' like amplitude has.

Trends
- [x] add graph legend
- [x] #2922  better date handling when date dropdown is selected. Should show calendar immediately
- [x] #2899 putting stickiness and lifecycle in a shown_as category is unintuitive. they are separate analysis classes that are hidden too close to simple trends breakdowns (issue #2782)
- [x] #2885 recategorize the per event filtering (total volume dau percentiles)
- [x] #2901 interval rounding (issue #2675)
- [x] ~~insights query returning no data (issue #2661)~~
- [ ] "Unique" property aggregator (#3077)

Sessions:
- [ ] should have breakdown
- [x] #2925 y axis is not immediately understandable (defaults to seconds)
- [x] #2926 clicking on data point crashes
- [x] #2883  ~~distribution is returning blank~~

Retention:
- [ ] current date is not immediately clear on how it will change the graph
- [x] #2884 ~~retention dashboard item not saving second item if it’s action (issue #2817)~~

Paths:
- [x] #2882  ~doesn’t show loading spinner just shows no events prompt when loading~
- [ ] show initial dropoff
- [x] #2923 - list of custom events is not loaded (issue #2836)

**Comment by paolodamico** [comment]
Referencing here the retention epic #2228 and the funnels epic #2697

**Comment by paolodamico** [comment]
Something from the retention missing but I think it's worth mentioning particularly is #2794, as it seems to be affecting all sorts of graphs. FYI @EDsCODE & @timgl

**Comment by paolodamico** [comment]
Think #3047 is worth considering too.

**Comment by paolodamico** [comment]
Adding another one #3087.

**Comment by paolodamico** [comment]
#2866 will also help here, particularly relevant for users doing web analytics

**Comment by paolodamico** [comment]
Following #3089 I think we definitely need to improve the accessibility of paths (i.e. colors need to be contrasting). The blue on blue thing is hard to read on the best of circumstances.

**Comment by EDsCODE** [comment]
#3124 3124

**Comment by jamesefhawkins** [comment]
#935 is relevant and has a few upvotes for legends on graphs

**Comment by paolodamico** [comment]
Tagging #3356 as relevant to include

**Comment by paolodamico** [comment]
@EDsCODE I think it might be worth moving the relevant issues to our project board and closing this, wdyt?

**Comment by EDsCODE** [comment]
Yeah, I think we can actually just close this and redraw the tasks. Also, it'll make more sense to split these by each insight because there's a lot to be added per insight
