### ISSUE TITLE
Release 1.23.0 parity project

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3338]
Collection of issues to achieve better parity

- [x] Bar chart of breakdown by breakdown rather than date
- [x] Refresh + select date range for entire dashboard (PR: #3363)
- [ ] Creating static cohorts by selecting users in interface (part 1 PR: #2952)
- [ ] Allow filtering on Distinct IDs on user properties (Issue: #3390)
- [x] Property filtering on multiple values (Issue: #3391)
- [x] Trend Legend (part 1 PR: #3434)

**Comment by macobo** [comment]
Note from call: Bar chart + table make extra 'All period' Interval option.

**Comment by timgl** [comment]
Closed for this release cycle
