### ISSUE TITLE
[Epic] Dashboards UX improvement 

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#3547]
**Goal:** To improve the dashboard experience and work out some of the bugs that have accumulated and gone unnoticed

- [ ] Refresh button timestamps should be obvious. The overall refresh button should also have a timestamp
- [x] sharing button confusing. It’s acting as a status button and an activity button but the prompt is confusing because it says “shared” when you can still click it to share
- [x] can’t scroll on presentation mode
- [x] Prompt to create more dashboard items
- [ ] Come up with names autofilled from relevant filters when you are about to add a new dashboard item
- [ ] standardize how layout works on different screen sizes (@fuziontech  should add details when this ticket is opened)
- [x] improve empty states #3514 

@corywatilo @paolodamico

**Comment by paolodamico** [comment]
Closes #3344?

**Comment by paolodamico** [comment]
Complements #3344

**Comment by corywatilo** [comment]
Took a quick stab at the ability to add new dashboard items _from_ the dashboard [here](https://balsamiq.cloud/sd0i9zq/pl0wjty/rE6C3).

![image](https://user-images.githubusercontent.com/154479/109920936-ff90ac80-7c88-11eb-8586-d6ab88757a8a.png)
![image](https://user-images.githubusercontent.com/154479/109920954-04556080-7c89-11eb-8a13-1c26c1647273.png)

Are we able to show a single list of all saved queries that are available to be displayed on the dashboard, or is that trivializing it?

**Comment by kpthatsme** [comment]
Ran into two bugs recently with dashboards:
https://github.com/PostHog/posthog/issues/3574
https://github.com/PostHog/posthog/issues/3573

**Comment by kpthatsme** [comment]
Ran into two bugs recently with dashboards:
[Issues with (multiple?) funnels rendering](https://github.com/PostHog/posthog/issues/3573)
[Issues with refresh behavior on retention](https://github.com/PostHog/posthog/issues/3573)

**Comment by liyiy** [comment]
Tackling scroll on presentation mode if it hasn't already been picked up yet~ 

For future reference, are Epics cross collaborative between people? And how does someone note that they're working on one of the issues of the Epic (besides just leaving a comment)?

**Comment by Twixes** [comment]
Superseded by #7517.
