### ISSUE TITLE
Release 1.24.0 bis – 12 April 2021

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3688]
Context:
- One of the main questions of the board meeting was startups vs enterprises. Key piece of the puzzle for that is VPC.
- Some questionmarks around data consistency for clickhouse last week
- Two new starters (Buddy and Sam)

Support hero:
Paolo

VPC
- Wrap up full automation of the helm chart. Set it up so that when you deploy the stack clickhouse is automatically started and wired up to our app in one step. This will be required for a one click deploy using cloudformation using EKS as well as GKE on GCP later
- Push for GCP Partner program (application submitted, there will probably be back and forth on Revenue)
- Setup cloudformation for EKS for one click deploy 

Plugins
- Stabilise the plugin API. PostHog/plugin-server#242 - imports, meta (PostHog/plugin-server#274), types, version requirements (PostHog/plugin-server#12), etc
- Figure out the architecture for queueing events for batch-uploading to an export destination... and then write a few proper data import/export plugins. S3 PostHog/plugin-repository#12. Postgres PostHog/plugin-repository#11. Snowflake PostHog/plugin-repository#13. Mongodb. Etc.
- Plugin logs (#3482) 
- Remove plugins opt-in behavior (#3557) 
- Optional: introducing plugins during onboarding flow #3764

Core analytics
- [ ] Data issues: Retention +  #3728 +  #3668 + refreshing dashboard
- [ ] Trailing DAU/WAU/MAU #3638
- [x] Break down more than 20 values #3589
- [ ] dashboard version history #3551
- [x] Check on experiments

- For Sam/Buddy:
  - Emails (as suggested by paolo)
  - Perhaps #3765 - interconnect the app more?

*Note: this is "1.24.0 bis" as we've decided to try monthly releases (per https://github.com/PostHog/ops/issues/207)*

**Comment by paolodamico** [comment]
## General discussion points
- Get emails working. Re-enable the ingestion event reminder (https://github.com/PostHog/posthog-cloud/pull/94) & weekly email report. As suggested by @macobo, happy to work with one of our new starters and/or @macobo. _Rationale: the email reminder ingestion has proven successful in increasing our activation conversion (at least in 1 step of the process), and the weekly email report is a test to drive engagement up._
- @EDsCODE I was going to add related to dashboards a few things that I think are going to push better engagement: sharing dashboards via email, Slack previews, collaboration/comments [intertwined with the version history that you've prioritized]. Let me know if you want to work together on this.
- We have a few experiments running (i.e. `remove-shownas`, `funnel-trends-1269`, `filter_by_session_props`, `3275-formulas`, `new-onboarding-2822`, `save-cohort-on-modal`) that have also been running for quite some time now. We need to check results and take relevant actions. I would like to encourage everyone who created an experiment to do a write up in the experiments repo (@kpthatsme has created a pretty useful template). 

## Myself
**List up for discussion, not a todo list yet.**
- Support hero instead of below?
- Tackle #2984. _Rationale: this is a core feature (most used feature) that causes confusion some time, or can be hard to understand for newcomers. I believe that a significant improvement in this experience here can help drive both activation & overall retention. There's also the consideration that a solution here could help us better serve non-technical users._
- Toolbar improvements. General UI/UX. In-place stats (e.g. changes in WAUs/DAUs). _Rationale: great engagement touchpoint right in our user's environment, could be a great driver of more engagement. Also a fairly used feature. Also, from sales calls we know that users do not understand this feature unless we walk them through it._
- Churn prevention. Investigate why are users drop us, and propose/implement solutions to address it. _Rationale: one key drivers of retention and worrying signal is users who have been retained for a "long" time and then drop._
- Related to a point above, work with @macobo on `filter_by_session_props` & `new-onboarding-2822` experiment results.
- Work with whomever picks it up on the features interconnection #3765
- Improvements/fixes from @corywatilo's [list](https://www.notion.so/PostHog-app-feedback-da8e96b246a04baf99dc864194977b15). _Rationale: overall user experience, geared towards better retention._

**Comment by macobo** [comment]
### General priorities

We will have two new people starting the next iteration. Would be great to hand them some high-impact projects that get them familiar with different parts of the product.

My suggestions:
- Emails (as suggested by paolo)
- Perhaps https://github.com/PostHog/posthog/issues/3765 - interconnect the app more?

### Karl

After last weeks plugins/ingestion are in a better place technically. I think it's time to get more people using them.

Priorities (plugins):
1. **Plugins 1.0 - increase adoption** Get more people familiar with plugins on cloud by introducing them during onboarding flow https://github.com/PostHog/posthog/issues/3764
1. **Performance** We don't have a large-size posthog postgres installation - let's create one via a plugin https://github.com/PostHog/posthog/issues/3762
2. **Plugins 1.0** Downsampling plugin https://github.com/PostHog/posthog/issues/3365
3. **Plugins 1.0**  Figure out architecture for retries in plugin server: https://github.com/PostHog/plugin-server/issues/273

Session recording:
1. Use plugin (1) to finally do https://github.com/PostHog/posthog/issues/3471 (multi-day filter in sessions) and verify it works on larger instances by default. This has been a frequently requested feature.

Other:
1. Actions on self-hosted can be a pain on moderately-sized instances after recent changes. A user did a lot of debugging for us, would be worth taking a look: https://github.com/PostHog/posthog/issues/3753, verifying and adding some indexes.

**Comment by mariusandra** [comment]
If I'll be working on Plugins, then these are the most important things to get done:

1. Stabilise the plugin API. https://github.com/PostHog/plugin-server/issues/242 - imports, meta (https://github.com/PostHog/plugin-server/pull/274), types, version requirements (https://github.com/PostHog/plugin-server/issues/12), etc 
2. Maybe deferred by https://github.com/PostHog/posthog/pull/3767? Action mapping in the plugin server https://github.com/PostHog/plugin-server/issues/235 - The async action mapping is a problem for a lot of self hosted users. I've also been hearing problems with webhooks for a while. We should fix this once and for all.
3. Figure out the architecture for queueing events for batch-uploading to an export destination... and then write a few proper data import/export plugins. S3 https://github.com/PostHog/plugin-repository/issues/12. Postgres https://github.com/PostHog/plugin-repository/issues/11. Snowflake https://github.com/PostHog/plugin-repository/issues/13. Mongodb. Etc.

Other integrations:
- Package.swift problem still with iOS - https://github.com/PostHog/posthog-ios/issues/13#issuecomment-806405489
- Ruby update request (`get_distinct_id`) https://github.com/PostHog/posthog-ruby/issues/3 -- could also get feature flag support

I'd also like to tack on a few things I promised to look at for some customers (or at least make issues for them):

- Custom columns in the events table https://github.com/PostHog/posthog/pull/2268
- Make actions that filter with just properties and don't require specifying an event name
- "Save as action" for any set of filters.
- Toolbar heatmap URL wildcards (show all elements for `/user/*`, not just `/user/123`) https://github.com/PostHog/posthog/issues/1411

**Comment by EDsCODE** [comment]
Misc issues:
- clickhouse data integrity issues
- funnel query suspect results #3728
- filter test accounts #3668 

Dashboards:
- refresh problems #3609
- dashboard version history #3551 
- dashboard insight presentation view #3551

**Comment by timgl** [comment]
I'm going to take myself out of availability. I didn't manage to allocate enough time to programming this sprint to be productive and with 2 new starters next week I don't think that'll improve.

Core analytics:
Some parity stuff:
- Trailing DAU/MAU/WAU (requested by beeperhq and two other tickets): https://github.com/PostHog/posthog/issues/3638
- Roll out formulas to everyone
- Figure out some discrepancies in data

**Comment by Twixes** [comment]
Myself:

- Plugin logs (#3482) (got dropped this sprint because of a rework of GeoIP jumping in its place - which did ship https://github.com/PostHog/plugin-server/pull/247)
- Remove plugins opt-in behavior (#3557) - but possibly still keeping them as beta?
- Ship "a member joined your organization" email (#3509)

And then happy to work on take on some stuff listed by people above.

**Comment by kpthatsme** [comment]
For me this sprint on the product side–

I'm going to be focused on a few things:
- Helping folks get in-flight experiments written up, resolved and logged in the [experiment repo](https://github.com/PostHog/experiments) - thanks @paolodamico for helping push this forward!
- Do some digging around cloud stability and its impact on business metrics
- Work w/ you all to understand why this ingestion dip occurred (likely an email issue) and make sure we get back to where we've been

**Comment by fuziontech** [comment]
For me on this sprint:

VPC VPC VPC:
- Wrap up full automation of the helm chart. Set it up so that when you deploy the stack clickhouse is automatically started and wired up to our app in one step. This will be required for a one click deploy using cloudformation using EKS as well as GKE on GCP later
- Push for GCP Partner program (application submitted, there will probably be back and forth on Revenue)
- Setup cloudformation for EKS for one click deploy

**Comment by paolodamico** [comment]
This has been released, closing.
