### ISSUE TITLE
[EPIC] - Insights UI/UX improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4475]
Continuing #4050. Documenting some UI/UX improvements we still need to do on insights:

## Design
Need some UI/UX design first before implementing (could be tackled by anyone, it's just something to consider).
- [ ] Make the RHS controls more compact (probably we can keep the title [e.g. "BREAKDOWN BY"] and action button in a single line).
- [ ] Formulas, some types of property aggregation, and other visualization options (e.g. cumulative) are advanced features that the majority of queries won't require. Should we hide these behind an advanced mode to make the experience easier for those times when you don't need it?
- [ ] Split cumulative (line chart) & value (bar chart) from display options.
- [ ] Funnels horizontal mode.
- [ ] Smart graph display #4330.
- [ ] Revamp pie chart #4403.
- [ ] Graphs empty & error states
- [ ] Revamp the person double click page.

## Implement
- [ ] New UI & migration to D3 #4758 #4568
- [ ] Revamp tooltips (date format, horizontal scrubbing, new UI, formatting, display options) #4154, #4156
- [ ] Fix UI of query titles and buttons (maybe worth moving back to the bottom). #4421.
- [ ] Suggest relevant properties #4166.
- [ ] Retention date is confusing. Use a normal date range.
- [ ] Graph legends (positioning, custom name) #4594.
- [ ] Update UI/UX for event/action picker #4749 and math property aggregator #4750.

## Done
- [x] Revamp table display #4646.
- [x] Graph table details (date ranges, event/breakdown display, total/avg column) #4700.

**Comment by paolodamico** [comment]
Oh wow is this outdated
