### ISSUE TITLE
Sprint 1.28.0 2/2 - Aug 16 to Aug 27

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5548]
## Focus / goals
> Sprint no. 1 of Diagnosing Causes (https://github.com/PostHog/product-internal/issues/107)

- **Focus 1**: ❗️ Figuring out how quantitative analysis looks like (#5543). Probably the most important outcome for this sprint.
- **Focus 2**: user paths (#5545)
- **Focus 3** (for Deployments & Infrastructure):  Identify and improve metrics against posthog/product-internal#119?

## Additional context
- Support hero: @fuziontech (week 1) & @Twixes (week 2)
- Feedback hero: @marcushyett-ph (week 1) & @paolodamico (week 2)
- @timgl / @yakkomajuri worth confirming if we'll do the code freeze, break the release & release before the offsite (because it'll essentially cut off the sprint length) or after the offsite.

**Comment by EDsCODE** [comment]
**Core Analytics**

These are short term planning until we have the paths query rewritten/broken up into extendable classes like we did for funnels. The complete list of features we're looking to add for paths are [here](https://docs.google.com/document/d/1TUxXZA1gMLhtsOnmk59p6I-7s7MdqoLQVyrtLbBNSE4/edit#) 

General:
- Leftover bugs

Karl
- Leftover materialized column work for performance improvement
- Funnel performance analysis 
- Blog post

Eric + Neil
- Paths performance improvement (query rewrite)
- quantitative analysis planning

Michael
- Get session recordings connect to funnel more precisely than we have now

**Comment by fuziontech** [comment]
## Team ¿Platform?
### Milestone:
- Diagnosing Causes

### Major **themes** for us this week:
- Ship improvements to paths tool on product
- Move needle on Reliability and Performance metrics for Cloud and for On Prem deployments

### Theme tasks:

#### Ship improvements to paths tool on product
##### P0
TBD - Will add if anything comes up that we can help with.
##### P1

##### P2


#### Move needle on Reliability and Performance metrics for Cloud and for On Prem deployments
##### P0 Supporting this posthog/posthog#4596
- [ ] posthog/posthog#5579
 [Jams & Karl]
- [ ] posthog/posthog#5580 [Jams & Karl]
- [ ] (Event Reliability) posthog/vpc#79 [Tiina]
- [ ] posthog/vpc#76 [Tiina]
##### P1
- [ ] posthog/vpc#76 [Tiina]
##### P2

#### Keeping the lights on
##### P0
- [ ] posthog/vpc#170 [Jams]
- [ ] posthog/product-internal#45 [Jams]
##### P1
- [ ] Docs Docs DOCS! posthog/posthog.com#1616 [Tiina]
- [ ] posthog/vpc#114 [Tiina]
##### P2

#### Extensibility

##### P0

- Cover anything needed to fully fix Super List of Issues Affecting CH Duplicate Distinct IDs #134

##### P1

- Build the foundation for data imports
- Build the mechanism for export from the beginning

**Comment by samwinslow** [comment]
Growth
===

Apologies for the late/scrappy update. My understanding of our focuses (foci?) for the upcoming sprint:

- Work with Marketing to bring top-of-funnel traffic to website, evaluate email gated signup flow
- Publicize the launch of Clickhouse + Open Source, make sure our docs are consistent and selecting deployment options is clear
- Build website infrastructure that will help us with future experiments & consistent updating
  - migrate our Markdown blog system to a CMS
  - set up multi-variant feature flags
  - various GH actions helpers
- Optimize our website performance by optimizing images, using more Gatsby plugins as needed

**Comment by paolodamico** [comment]
Sorry forgot to update this on Friday. For visibility, sharing context that we talked about during the spring planning for **Core Experience Team**.


In general terms, we'll likely be working around this during the sprint, but we're waiting for our standup today now that @mariusandra is back.
- Few relevant outstanding P1, P2 bugs & improvements around nailing funnels (see "1.28" column on https://github.com/orgs/PostHog/projects/9 for details).
- Work with Core Analytics, Design & Product on figuring out the right solution for #5543 (quant analysis).
- Work with Core Analytics on building Paths feature (details [on this doc](https://docs.google.com/document/d/1TUxXZA1gMLhtsOnmk59p6I-7s7MdqoLQVyrtLbBNSE4/edit))

**Comment by Twixes** [comment]
Completed.
