### ISSUE TITLE
Saved Insights 🐛 List

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#6036]
We recently shipped a new saved insights feature hidden behind a FF - #5702

Let's collect all saved insights bugs that our team might find while dogfooding it. Feel free to edit this issue to add to this list.

All fixes will be merged into branch `fix/saved-insights-bugs-6036`

- [X] Funnel insights don't take up the full width - #6039
- [X] Add CTA button to empty insights table for new users w/o insights. - #6042
- [x] The create / edit insight page needs a header that reflects the page state. "Create insight" or "Edit insight" should suffice - #6045
- [ ] ~~When a saved insight is loading, the placeholder for the graph says 'We couldn't find any matching events. Try changing dates or pick another action or event.'~~ See https://github.com/PostHog/posthog/issues/6036#issuecomment-923313159
- [X] Refactor `Insights.tsx` - #6037
- [X] List and Grid buttons should look nicer. - #6048
- [X] Back button doesn't work when viewing a saved insight - #6047
- Add yours here...

**Comment by clarkus** [comment]
>  Add CTA button to empty insights table for new users w/o insights.

This should be an empty state with description, not just a restatement of the CTA. There is a design at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3245%3A37002

**Comment by Twixes** [comment]
A couple checkboxes to tick from me:

- [x] Name and Description text areas look very much out of place and take up precious real estate requiring the user to always scroll down to do anything. I think we could use some real UI design expertise here – @clarkus?
![Zrzut ekranu 2021-09-20 o 20 49 01](https://user-images.githubusercontent.com/4550621/134058188-0bdaee44-7b98-4f53-9425-001d76ec04af.png)
- [x] These two should have a margin between them:
	![Zrzut ekranu 2021-09-20 o 20 49 39](https://user-images.githubusercontent.com/4550621/134058113-64048feb-5daf-45df-8cc9-11f3173b0d73.png)

I also feel like we should change the icon for "Insights" in this case. It's still the same as when it represented what now is "Explore", which I fear could make users confused. It still feels a bit weird to me, being used to its previous iteration.
![Zrzut ekranu 2021-09-20 o 20 50 17](https://user-images.githubusercontent.com/4550621/134058727-75a9179b-21b6-4208-8f0b-c4a16887ba92.png)

**Comment by clarkus** [comment]
>  Name and Description text areas look very much out of place and take up precious real estate requiring the user to always scroll down to do anything. I think we could use some real UI design expertise here – @clarkus?

@Twixes this is mostly [matching the design.](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3245%3A33481) There should be a header above those fields. 

We decided to collect this information up front in order to make saving immediate. We could prompt for this information on save, but [when this design was happening](https://github.com/PostHog/posthog/issues/3408#issuecomment-892921935) we were focused on making saving much more explicit and immediate. 

>  These two should have a margin between them:

They're two buttons with no spacing between them, collapsed borders, and no rounding on the adjacent sides. See it in figma at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=3245%3A32428.

<img width="156" alt="Screen Shot 2021-09-20 at 12 41 46 PM" src="https://user-images.githubusercontent.com/254612/134064906-667b9552-af7e-4204-98c3-30791f5053a1.png">

> I also feel like we should change the icon for "Insights" in this case. It's still the same as when it represented what now is "Explore", which I fear could make users confused. It still feels a bit weird to me, being used to its previous iteration.

Icons are very challenging for this. I would eventually like to drop the icons and instead [rely on clear labeling](https://github.com/PostHog/posthog/issues/5346) for all the main features. Shorter term, we could align the icons more by changing both to use the same core icon type, and overlay a `+` symbol for the explore case. I can make some updates here to see if there are any easy fixes.

**Comment by Twixes** [comment]
Thanks @clarkus!

Re: Text & Description I see. I think currently they look significantly sloppier than in the design, because Description is unintentionally a different, larger size than Text. It also seems though that the design does not have a variant for wider viewports, which is where these text boxes create a ton of wasted whitespace on the right.

Re: List/Card, looks great in the design. Implementation-wise seems like this should just be an Ant Design [`Select`](https://ant.design/components/select/) component as opposed to two `Button`s.

**Comment by kpthatsme** [comment]
Adding a new one: 

- [x] back button doesn't work when viewing a saved insight

Repro steps:
- Go to Insights, click on one
- View the chart
- Back arrow - modifies the chart and keeps you in the "Explore" tab instead of going back to Insights

**Comment by alexkim205** [comment]
> * [ ]  When a saved insight is loading, the placeholder for the graph says 'We couldn't find any matching events. Try changing dates or pick another action or event.'

@rcmarron Been digging into this, and I think this happens in saved insights because [we render](https://github.com/PostHog/posthog/blob/d3b1a55f825c9e0e5e5dfa9d99dfea3b28f5f2bd/frontend/src/scenes/insights/InsightContainer.tsx#L171) `<Loading/>` over our insight containers. Problem is that in our saved insights, the insight containers start without any data, which leads to a loading state being rendered over an empty state. 

It looks like this is an existing bug in today's trends line graphs on hard initial refreshes. You can see a flash of the empty state before a loading indicator overlays it.

https://user-images.githubusercontent.com/13460330/134076524-d77e0744-772e-44ce-bac9-a7dcc5e91366.mov

I think we have a plan to revisit initial empty states in the future under the scope of https://github.com/PostHog/posthog/issues/3982#issuecomment-876656269 so I'll leave this out of saved insights for now, but definitely a bug to fix later.

**Comment by alexkim205** [comment]
> Re: List/Card, looks great in the design. Implementation-wise seems like this should just be an Ant Design [`Select`](https://ant.design/components/select/) component as opposed to two `Button`s.

Maybe antd's [`Radio` button variant](https://ant.design/components/radio/#components-radio-demo-radiogroup-options) would be more appropriate?
