### ISSUE TITLE
Remaining paths work

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6157]
#5825 and #6066 are behind the feature flag `new-paths-ui`

Link PR inline with the item it fixes

**UI:**
- [ ] Path cards should show entire label when hovered over. Right now it's shortened
- [x] (ready for review: #6161)  Need to show numbers on the card without hover otherwise it's hard to gauge general numbers
- [ ] Cards should show both/ either/or to and from numbers. It's hard to figure out how many people arrive at a certain node from another. Or put this information when clicking/hovering on an edge (connection between nodes)
- [x] (#6175) Cards don't disappear when query returns nothing and the viz goes into empty state [Ref 1]
- [x] ( https://github.com/PostHog/posthog/pull/6179) Add ability to click on numbers in the dropdowns and show person modal - @neilkakkar 
- [x] (#6200) Add menu button for path cards that provide ability to set end points, and exclude events
- [x] (#6160) Connect funnel to paths (need button on funnels and the special start/end point statuses when a funnel is selected)
- [x] (#6198) Funnel to paths dropoff connections
- [x] (#6175) Delete button for start and end point should have feedback when hovering
- [x] (#6160) Delete button is covered by long path items [Ref 2]
- [ ] Last node person counts shouldn't be grouped under dropoff by default. We currently count all the persons at the end of a path as dropped off but we don't have data to tell whether they dropoff or continue through
- [x] (#6209 ) Add funnel paths dropdown to the new funnel UI and style better to match  (#6200)
- [ ] Dashboard item in viewports should scale 
- [ ] Dashboard item should work with optional dashboard item background colors [Ref 3]
- [ ] The path visualization rerenders based on horizontal window but not vertical. (Try resizing the window and you'll notice the height is static but width will scale accordingly) [Ref 4]

**API**
- [x] Path weighting to determine useful paths to see. Some cluttered path areas are useless because there are too many tiny lines to track. Doing this right should help solve the UI clutteredness

Ref:
1. <img width="1258" alt="Screen Shot 2021-09-28 at 2 17 13 PM" src="https://user-images.githubusercontent.com/13127476/135143230-ab33ae29-b451-471b-811c-a23d3728e2d4.png">
2. <img width="623" alt="Screen Shot 2021-09-28 at 2 15 49 PM" src="https://user-images.githubusercontent.com/13127476/135143008-5da2745a-cbe3-4434-837f-32a764165f1c.png">
3. <img width="720" alt="Screen Shot 2021-09-28 at 2 17 51 PM" src="https://user-images.githubusercontent.com/254612/135167166-6103f6e7-3525-470e-9a51-f1693c1ea3c1.png">
4. <img width="794" alt="Screen Shot 2021-09-28 at 2 20 23 PM" src="https://user-images.githubusercontent.com/13127476/135143717-36c395e2-2d1d-423f-ad5f-8ab47e34c8ee.png">

@liyiy @neilkakkar @EDsCODE @clarkus

**Comment by clarkus** [comment]
Some feedback items I'm tracking from figma that might possibly be in scope:

- Smarter truncation of path item names in the collapsed state
- Fully described (no truncation) of path item names in the expanded state
- ~~Wildcards in start / end path parameters & exclusions~~ https://github.com/PostHog/posthog/pull/6205

**Comment by neilkakkar** [comment]
> Cards should show both/ either/or to and from numbers. It's hard to figure out how many people arrive at a certain node from another

Or hover on links to get count for them? Could make the links (the blue parts on Paths) clickable as well, and show these specific people?

**Comment by clarkus** [comment]
> Or hover on links to get count for them? Could make the links (the blue parts on Paths) clickable as well, and show these specific people?

Yup we could show the persons modal the same way we do in funnels.

**Comment by EDsCODE** [comment]
Closing this as most of it has been done. The remaining tickets were broken into separate tickets for easier managing
