### ISSUE TITLE
Recording playback bugs + internal feedback

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#6483]
An issue to track feedback + issues on the new recording playback experience.

🐛 Bugs:
- [x] The new progressive loading logic behaves non-intuitively for long recordings. Try skip ahead ~40 minutes here: https://app.posthog.com/recordings?sessionRecordingId=17c82b1e00d5e-0fbae39a44ef0f-123b6650-1aeaa0-17c82b1e00e11e9 (from @macobo)
- [x] If playback catches up to buffering, the player pauses and doesn't restart. Repro's consistently for me if my speed is set to 16x - especially if I throttle the connection (from @rcmarron)
- [x] If you use the "Skip back X seconds" to move from buffering to non-buffering, the "buffering..." sign never goes away
- [x] Hard to repro, but sometimes the player gets stuck in a "always buffering" state (the recording is playing in the background, but the buffering sign is still shown). I think it only happens on recordings where the entire recording is returned in a single request. #6969
- [x] If you click the thumb in the player repeatedly, it jumps backward a couple of times.

https://user-images.githubusercontent.com/4813045/139320274-4494aee8-b769-4c36-af55-fea28467a157.mov

- [x] If you click on recent recording (<1min ago and <1min duration), timestamp is NaN:NaN:NaN #6969
- [x] Clicking 1 pixel above or below seekbar doesn't seek the thumb #6962

🗣 Feedback:
- https://github.com/PostHog/posthog/issues/6473

**Comment by alexkim205** [comment]
Some more outstanding tasks:

- [x] @rcmarron Handling multiple window ids
- [x] @rcmarron Fix skip-inactivity
- [x] @rcmarron Fix pagination on the recording list
- [x] @alexkim205 Jumpy highlight box when current event range changes. 
- [x] @alexkim205 Meta card goes back into a loading state after events have been loaded.
- [x] @alexkim205 General scrolling lag in event list
	- [x] Get rid of premeasuring each row
	- [x] Limit length of description 
	- [x] Clicked "Text" -> descriptions become 1 line -> no more pre-measuring
	- [x] Middle truncate page urls `/person/08d99252b8c3-...`

**Comment by alexkim205** [comment]
Responding to some of @paolodamico's feedback here - #7278 

> - Filtered events are not highlighted as per design.

As far as I can see in the mockups, filtered events aren't supposed to be highlighted, but rather events are highlighted manually by the user. Highlighting events in the list would be work that would be bundled with the recording options action button thats pending WIP.

> - Filtering UI in the recordings list is not consistent with the rest of the app.

Recording filtering is work that's pending. We used Fuse to move quickly here but it's work that should be done for v2 of recordings.

> - Happened a couple of times, app will continue skipping inactivity while the user is still very clearly moving. Further, if you click on the pin and jump directly, the recording playbacks properly. Try watching this recording without skipping anything and you'll see this.

Definitely a bug I've been seeing as well. Might timebox this to half a day and figure this one out.

> - Pagination in recordings list is inconsistent with the rest of the app. Further the experience is painful, the entire table freezes and scroll position stays at the bottom.

@rcmarron  has made some nice performance optimizations captured in this issue #7247. Most of the fixes are in-flight or have already been merged.

> - Searching “rage” in the event list at a recording yields no rage click events but a bunch of page views, searching “ragec” works.

I believe this happens because "rage" is one letter change away from "page" and there are no rageclicks to show. Might be worth lowering the search threshold to show exact matches only, but I'm a fan of the fuzzy search in general and think this one's fine to leave alone.

> - Redacted box doesn't seem to be showing up every time it should. For instance, watch a recording on a /person/{id} page and you'll see the right side table of properties not showing the property values, yet the box is also not shown.

This might require some deeper digging, but I suspect it's because these recordings were captured with an outdated version of posthog-js that didn't inject a classname given to redacted areas. All recordings taken before this change will not redact correctly.

**Comment by clarkus** [comment]
Responding to specific items from https://github.com/PostHog/posthog/issues/7278

> @clarkus should the redacted boxes have rounded corners to better match the rest of the UI? Further, perhaps having them a bit less dark?

I think it just needs to look obviously overlaid with an uncommon pattern. We're not so much aligning to our UI as we are to the instrumented product's UI. If that redacted element is rounded, then we could round, but otherwise just overlaying with the pattern seems like it works. 

> Can we do a nicer buffering state ? Even just changing the font would go a long way. CC @clarkus

Updated design that uses our long-loading state from tables. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5400%3A39327

> Should we allow users to hide certain events that will always be useless for them in recordings? e.g. $feature_flag_called for us. My concern would be with an extra configuration that can add confusion. CC @clarkus

> Related to the above, should we always hide certain PostHog events that are probably going to add very little value? e.g. $identify, $groupidentify, ...

There are similarities to the options we implemented for paths - generally there are context-specific settings that we might offer to highlight important events, or to mute noisy events. These options could be available specifically in the events list and would cease to apply once that recording was closed. Another option is to have project level settings that exclude noisy events. Thoughts?

**Comment by rcmarron** [comment]
Responding to a few more of @paolodamico 's comments from #7278 

> Filtering UI in the recordings list is not consistent with the rest of the app.

Definitely agree with this. It'd be great to make filtering across the app consistent. I've stumbled on a few recordings of users struggling to find the person property filters. I think there's a challenge with the UX because it's pretty different from insights - in insights you're building something, so the query builder is the primary thing and happens to play the role of filtering. On recordings, filtering plays a more secondary action. @clarkus I think I remember you saying that you had some sketches of more consistent filtering?

> When buffering it seems we have to load everything in sequence instead of the point I care about. See this recording where I wanted to look at a rage click at ~1:00:00.

This can painful. Unfortunately, it's a result of the way rr-web works. Basically, we get a full snapshot at the beginning of the recording (or on page reloads), and then, everything is just a delta from there. So playing each frame depends on the frame before. I could think of a couple solutions - like having the server create "generated full snapshots", but at that point we'd be rewriting rr-web in python. Before doing anything along those lines, I'd rather revisit how we're storing recordings. I think we can make loading much faster if we move the recordings out of clickhouse and to s3, and while that doesn't solve this exact request, I think it'd go a long way to the root issue of "let me quickly see the moment I care about". (Also it would get us longer retention on recordings)

> Happened a couple of times, app will continue skipping inactivity while the user is still very clearly moving. Further, if you click on the pin and jump directly, the recording playbacks properly. Try watching this recording without skipping anything and you'll see this.

Yeah, this is an rr-web bug. I dug through rr-web to figure it out, and I think it's pretty baked into how they built that feature. Implementing our own "skip inactivity" is a work in progress. Adding to the list above for tracking.

> Pagination in recordings list is inconsistent with the rest of the app. Further the experience is painful, the entire table freezes and scroll position stays at the bottom.

Right now, it's the same as the persons page. We could make it like the events page with a "load more", but we it would be an expensive query to make it like feature flags with a "1-10 of 52". I assume you think we should move to a "load more" model? @paolodamico Also, I think improving the query speed will help this a good amount. Either way - adding this to the list above.

**Comment by paolodamico** [comment]
Thanks everyone! 👍 on all points, unless there's a comment below.

> As far as I can see in the mockups, filtered events aren't supposed to be highlighted, but rather events are highlighted manually by the user.
For @alexkim205 & @clarkus, what are we solving by letting the user manually highlight events in a single playback session? Seems like filtering for an event/action on the recordings list, coming from a funnel step or a path step is the strong signal here. I don't imagine myself manually highlighting an event for a single playback session.
--------

I've opened a separate issue to discuss the Fuse search results as it's something that affects the entire app.

--------

Re pagination, I'll defer to @clarkus, but I'm not a fan of the Load more approach. I think either infinite scroll or pages is the way to go here.

**Comment by clarkus** [comment]
> Definitely agree with this. It'd be great to make filtering across the app consistent. I've stumbled on a few recordings of users struggling to find the person property filters. I think there's a challenge with the UX because it's pretty different from insights - in insights you're building something, so the query builder is the primary thing and happens to play the role of filtering. On recordings, filtering plays a more secondary action. @clarkus I think I remember you saying that you had some sketches of more consistent filtering?

This has a lot in common with how users search for events or actions. It wasn't implemented, but there is a mostly complete design for filtering for events at https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1121%3A143574. More context at https://github.com/PostHog/posthog/issues/5546. This needs to be re-evaluated as it predates the recent table clean up work.

**Comment by paolodamico** [comment]
@clarkus as you suggest, I think it's worth coming up with a pattern that works across multiple tables and use this opportunity to start implementing it. That being said, you have more context on what's best to prioritize in terms of design work.
