### ISSUE TITLE
Figure out funnel vertical breakdown

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7409]
We have the `5733-funnel-vertical-breakdown` in an ambiguous state because it has some outstanding bugs to fix before we can ship it. We need to either fix those bugs and release it to everyone or scrap all these changes.

**Comment by alexkim205** [comment]
Additional "related" bugs to address:

- [ ] Figure out the vertical breakdown FF #7409
- [ ] Showing/hiding “Other” breakdown is buggy #6560
- [ ] Funnels - person modal can’t be opened #7275
- [ ] Inconsistent empty state in funnels #7373
