### ISSUE TITLE
Nail insights experience - 1.31.0 2/2 (Core Experience)

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7412]
Posting from original discussion on [Google doc](https://docs.google.com/document/d/1-sSrZewKm--A1ivJt_nMPc5lGOCNJRXqMzCzjbysiUo/edit#).
- Let's try to keep the conversation in individual issues to avoid bloating this issue.
- Please update the main comment directly.
- If you add something, make sure it links to an individual issue.

**Legend**
- 🔻Lower priority
- 🎨Requires design input (blocked)

## General insights
General bugs that affect multiple insights.
Assignees:  @pauldambra @Twixes
- [x] Incorrect reporting on Insights #7347
- [x] Dashboard or insight fails to load #6285
- [x] Insight render with wrong data #7153
- [x] Renamed graph series not saving #6688
- [x] Better tooltips on insight tabs #7292
- [x] Loading state persists on insight after heavy query #7277
- [x] Breakdown null UX #3974
- [x] Bug loading saved insights #7411
- [ ] Legend visibility implementation inconsistency #6102 🔻
- [ ] Remove funnelLogic mounting from all DashboardItems #7376 🔻
- [ ] Decouple insights from URL #4329 🔻

## Taxonomy filter
Bugs & improvements related to the taxonomy filter of events, properties, cohorts, autocapture, ...
Owner:  @mariusandra @paolodamico
- [x] Default to a category #5381
- [x] Tabs structure / scrolling #5962 ~🎨 Design done~ https://github.com/PostHog/posthog/pull/7475
- [x] Elements tab #5312
- [x] Key bindings #7458
- [ ] Improving client-side search #7368
- [x] Hide events in event select box with no 30-day usage #4791
- [x] Sort list by popularity/relevancy #5309; PR: #7426
- [ ] Only show properties relevant to each event #4166 

## Funnels
Funnels-only bug fixes
Owner:  @alexkim205
- [x] Figure out the vertical breakdown FF #7409
- [x] Showing/hiding “Other” breakdown is buggy #6560
- [x] Funnels - person modal can’t be opened #7275
- [x] Inconsistent empty state in funnels #7373

## Date/time support
Adding proper support for datetime properties.
Assignees: @pauldambra & @Twixes 
- [ ] Allow filtering with date/time props #6619
- [ ] Improve custom date range selector #2779 🔻

## Insight tooltips
Revamp / fixes to the tooltips in an insight graph
Assignees: @alexkim205 & @paolodamico 
- [ ] Insight tooltips are painful #7370 **⚠️ Should be tackled with #4705 as the solutions are intertwined**
- [ ] Increase hover area for smaller data points #5698
- [ ] Cohorts tooltip displays ID instead of cohort name #7369
- [x] Allow clicking on user list for overlapping data point #4775
- [x] Use all available white space #6668

## Dashboards
Anything related to Dashboards and making them awesome!
Assignees: @Twixes & @pauldambra 
- [x] Dashboard discrete grid - consistent layout #4312
- [ ] Weird lag with dashboard date ranges #7222
- [ ] Dashboards and date filters #6712 🎨
- [ ] Lifecycle insight not saving filters to dashboard #4787
- [ ] Make dashboards UI great #7517 🎨
- [ ] Hourly graphs take too much space #2656
- [ ] Dashboard editing & locking #3636 🎨 (UX)
- [x] Insights added to dashboard don't show up #7123

----------------

# 🙅 Deprioritized 
The following elements were deprioritized from the sprint on Dec 6th. The "actor modal" theme was handed over to the Core Analytics team due to the scope of the bugs.

## Insight improvements
Improvements / new functionality to multiple insights
Assignees: **TBD**
- [ ] Intuitive UX for bar value chart #4654 🎨
- [ ] Clean up UX for DAU/WAU/MAU #6254 🎨
- [ ] Improve legends for lifecycle #4041
- [ ] Improve UX for formulas in trends #3375 🎨
- [ ] Breakdown by cohorts is confusing #4696 🎨
- [ ] Custom units y-axis #4344 🎨
- [ ] Insight refresh disabled state is misleading #7284
- [ ] Insight time selector resets are annoying #7285
- [x] Legend key in chart #4594

## Compare previous
Compare previous functionality used across insights
Assignees: **TBD**
- [x] Make “compare previous” great! #4705 🎨 **⚠️ Should be tackled with #7370 as the solutions are intertwined**
- [ ] Stickiness tooltip with compare previous #5473
- [ ] Reset button doesn’t clear compare previous #5916

## Pie charts
The Pie Chart
Assignees: **TBD**
- [ ] Revamp pie chart UI #4403
- [ ] Data isn’t displayed properly #5695
- [ ] Only displays totals in breakdown #5696
- [ ] NaN in pie chart #4644
- [ ] Can’t add pie chart to dashboard with breakdown #6602

## New insight visualizations
Adding new ways to display insights
Assignees: **TBD**
- [ ] Area chart #7372
- [ ] Big bold number #6172

## Saved insights
Related to the saved insights view
Assignees: **TBD**
- [ ] Revamp the card view #7374

**Comment by paolodamico** [comment]
EDIT: @Twixes approach of marking stuff done in the list once a PR is **fully ready** makes sense, because we also see the issue next to it and whether it's open or closed (we know it's fully merged once it's closed).

~I suggest only marking stuff as done once it's merged.~

**Comment by Twixes** [comment]
There's a good argument for that, though I for one in practice have found it much easier to parse what to-dos remain if the items that have a PR out are marked

**Comment by paolodamico** [comment]
Leftover items prioritized for next sprint can be found at #7581.

**Comment by paolodamico** [comment]
Getting ready to close this. I believe we didn't finish some of the items we planned to, should we reprioritize them this sprint? If we do, what are we removing from next sprint?
- Taxonomy filter (@mariusandra). #7368 & #4166. Think it's worth keep working on this. Thoughts?
- Insight tooltips (@alexkim205). #7370 (which would basically fix all other bugs?). Thoughts?

**Comment by paolodamico** [comment]
Alright #7581 has been updated per standup conversation, this sprint is now at a close.
