### ISSUE TITLE
Core Experience sprint planning - 1.32.0 1/2

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7581]
Support hero: Marius (W2), Paolo (W4)

- @mariusandra: 1 week here (sick family), 1 week support hero, then 2 weeks on holiday
- @clarkus: 1 week here, off 2 weeks, 1 week back
- @paolodamico: 1 week here, off 2 weeks, 1 week support hero
- @alexkim205: 1 week here, off 2 weeks, 1 week back
- @rcmarron: 1.5 week here, off periodically after, working ~1.5 more weeks
- @pauldambra: 3 day weeks each of the next 4 weeks
- @Twixes: 1.6 weeks now, out for 1.4 weeks, then back for 1 week

## Recordings
Assignees: @rcmarron & @alexkim205 
- [ ] Link trends to recordings [Close out diagnosing causes]
- [ ] Link funnels & paths to recordings. @rcmarron it's quite key to get this working, from the standup I think we might need Core Analytics help here? Worth involving them as quickly as possible. [Close out diagnosing causes]
- [x] Get the multiple window_id player live
- [x] Fix rrweb bug

## Date/time support
Adding proper support for datetime properties.
Assignees: @pauldambra & @mariusandra 
- [ ] Allow filtering with date/time props #6619
- [ ] Improve custom date range selector #2779
- [ ] Full timezone support on insights #TBD [stretch goal]

## Dashboards
Anything related to Dashboards and making them awesome!
Assignees: @Twixes & @pauldambra 
- [ ] Make dashboards UI great #7517 🎨
- [ ] Revamp the card view (saved insights) #7374 (@mariusandra)
- [ ] Dashboards and date filters #6712 🎨
- [ ] Hourly graphs take too much space #2656
- [ ] Insight refresh disabled state is misleading (insights included) #7284 
- [ ] #7376
- [ ] #6439
- [ ] #3362
- [x] Weird lag with dashboard date ranges #7222
- [ ] Lifecycle insight not saving filters to dashboard #4787 (*)

## Insight improvements
Improvements / new functionality to multiple insights
Assignees: @alexkim205 
- [x] Insight time selector resets are annoying #7285
- [x] Disconnect all insight filters from the URL, and connect them directly to `insightLogic`.

## Insight tooltips
Revamp / fixes to the tooltips in an insight graph
Assignees: @alexkim205 & @paolodamico (reviews)
- [ ] Insight tooltips are painful #7370 **⚠️ Should be tackled with #4705 as the solutions are intertwined**
- [ ] **(if applicable after 7370)** Increase hover area for smaller data points #5698
- [ ] **(if applicable after 7370)** Cohorts tooltip displays ID instead of cohort name #7369

------

# 🙅 Deprioritized

## Taxonomy
**State**: Deprioritized to work on leftover recordings & insight tooltips work. We'll attempt to work on the product side this sprint (define scope, design, ...) CC @clarkus.
**Owner**: @alexkim205; working with @rcmarron
**Goal**: Users should understand events, actions & properties others have set-up (more details in [the roadmap](https://github.com/PostHog/product-internal/pull/232)).

[Taxonomy: Scope and Task Breakdown](https://github.com/PostHog/posthog/issues/7589)

## Taxonomy filter
**State**: Deprioritized due to very limited availability this sprint of assignees, we should keep it on our radar.
Bugs & improvements related to the taxonomy filter of events, properties, cohorts, autocapture, ...
Assignees:  @mariusandra @paolodamico
- [ ] Improving client-side search #7368
- [x] Only show properties relevant to each event #4166

**Comment by mariusandra** [comment]
Three more insight (funnels) related bugs that would be great to fix. Thanks @macobo for reporting

- https://github.com/PostHog/posthog/issues/7708
- https://github.com/PostHog/posthog/issues/7724
- https://github.com/PostHog/posthog/issues/7725

**Comment by paolodamico** [comment]
# Retrospective

### Recordings
@rcmarron
- Trends <> recordings will be ready (https://github.com/PostHog/posthog/pull/7852)
- Connecting funnels/paths <> recordings outstanding. Need to sync with Core Analytics to integrate.

### Date/time support
@pauldambra
- Progress on identifying date/time attributes.
- Likely to fall over unto next sprint.

### Dashboards
@Twixes 
- Most of stuff essentially finished.
- A lot of uncertainty on the design/UI (we could've done it before all this).
- Stuff will fall over unto next sprint.

### Insight tooltips & insight improvements
@alexkim205
- First iteration of tooltips ready. Before holidays there was some indecision on how to show multiple series in tooltips. Run with a stop-gap solution. Was waiting for more team discussion on this. Was not sure who to involve.
