### ISSUE TITLE
Close out diagnosing causes

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7614]
We're in the last stages of [diagnosing causes](https://github.com/PostHog/product-internal/blob/main/requests-for-comments/2021-10-11-diagnosing-causes-success.md) and have only got a few more steps to get it over the line and officially close this milestone 🎉.

# Outstanding items

- [x] Connect person modal to specific relevant recordings (at least funnels, paths & correlation analysis). **Owner: @rcmarron**
- [ ] Users can immediately jump to relevant part of the recording based on the funnel, path or correlation analysis source. **Owner: @rcmarron**
- [ ] Update Paths documentation. **Owner: ???**
- [ ] Update funnels documentation (how to understand and improve conversion). **Owner: ???**
- [ ] Update recordings documentation. **Owner: @rcmarron**
- [x] Succeed in achieving 1,000 conversions analyzed per week ([dashboard](https://app.posthog.com/dashboard/23883)). **Owner: @paolodamico**
- [ ] Succeed in achieving 900 recordings analyzed per week (can't be measured yet, feature is pending). **Owner: @paolodamico**

**Comment by paolodamico** [comment]
- @EDsCODE @rcmarron who will own the missing connection step between funnels/paths & recordings? I believe this initially Core Analytics scope?
- @EDsCODE who would be the right person to own the Paths documentation?
- @neilkakkar I think you could own the Funnels documentation as you have all the context from correlation analysis?

**Comment by rcmarron** [comment]
I can own the missing step, but I'll likely need some help from core analytics on a few of the modals. But happy to take general ownership. Also, how are we thinking about the priority of this vs taxonomy/collaboration? Maybe it's a thing for 1.32.0 2/2

**Comment by paolodamico** [comment]
Perfect @rcmarron, thanks! @EDsCODE @neilkakkar maybe you can help Rick with this? It's the key thing we're missing to close out this milestone.

**Comment by EDsCODE** [comment]
Yup, will do

**Comment by paolodamico** [comment]
https://github.com/PostHog/posthog.com/pull/3124 is signalling the closing of this milestone, so closing this issue.
