### ISSUE TITLE
Cohorts Epic

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#7762]
Cohort analysis is fundamental to product analytics in comparing different segments of user. Some enhancements and bugs that will greatly improve experience and usability

**Enhancements:**
- [x] Insight based cohorts #7569 
- [ ] Flexible time filtering on action based cohorts (more than just the predefined time frames)
- [ ] AND based filtering https://github.com/PostHog/posthog/issues/6186
- [ ] Speed up cohort filtering https://github.com/PostHog/posthog/issues/5854
- [ ] Analysis of cohorts https://github.com/PostHog/posthog/issues/3032
- [ ] Filter by property on action based cohorts https://github.com/PostHog/posthog/issues/6299
- [ ] [TBD] generic "active user" cohort. Action based cohort that doesn't require specifying an event just "any activity" in last X amount of time

**Bugs:**
- [ ] https://github.com/PostHog/posthog/issues/6950
- [ ] Cohort page doesn't show more than 100 https://github.com/PostHog/posthog/issues/7390
- [ ] Related to above, cohort filtering doesn't show more than 100 cohorts
- [ ] https://github.com/PostHog/posthog/issues/4696
- [ ] https://github.com/PostHog/posthog/issues/5565

**Comment by macobo** [comment]
If the goal is to improve cohorts long-term, I think this is missing a very important piece:

1. What problem are cohorts solving?
2. How to solve for these problems with groups in mind?

Without solving for groups our B2B users won't receive any benefits and we end up fragmenting the app. I don't have confidence it's as simple as "groups can belong to cohorts" without digging deeper into why and how to use this feature and how groups slot in there.

I think it's worth conducting some user interviews and digging into user feedback as well.

cc @marcushyett-ph for product thoughts

**Comment by macobo** [comment]
These tickets are great and do summarize a lot of known issues about cohorts to date.

However if the goal is to improve cohorts long-term, I think this is missing a very important piece:

1. What problem(s) are cohorts solving?
2. How to solve for these problems with groups in mind?

Without solving for groups our B2B users won't receive any benefits and we end up fragmenting the app. I don't have confidence it's as simple as "groups can belong to cohorts" without digging deeper into why and how to use this feature and how groups slot in there.

I think it's worth conducting some user interviews and digging into user feedback as well.

cc @marcushyett-ph for product thoughts

**Comment by marcushyett-ph** [comment]
+1 to the point on what are the problems we're solving for. Happy to support with any product thinking here to help us prioritize.

**Comment by EDsCODE** [comment]
Excellent point. Should've clarified that this ticket was just collecting all the open cohort ideas + more. The bugs definitely should be addressed as it makes the cohorting unusable.

Several of the enhancements + the new ideas on the enhancements actually came about from my own exercise in trying to do some deeper analysis. Specifically, "how successful is session recordings." We need to standardize our measurement of success of new features but a basic pattern I was missing was a clear way to compare actors who have used session recordings vs (active) actors who have never used session recordings. 

Open to rebuttals on usefulness here but cohorting behaviors effectively both for individual people and groups seems to be a fundamental pattern that we haven't quite nailed yet.

**Comment by clarkus** [comment]
From a UX perspective, it is interesting that cohorts, persons, and groups are all pretty separate in the product today. I think it's also worth considering https://github.com/PostHog/posthog/issues/7643 as a big part of this. Words matter and if we can get this figured out and consistent now, we'll be set for making more improvements later. Count me in for helping figure this one out.

**Comment by EDsCODE** [comment]
From call with Karl

- agreement on needed improvements to general ability to improve how users can be segmented in many different ways to drive better insights
- the path there is unclear and there's work to be done in understanding the depth of groups functionality alongside cohorts and when one makes more sense than the other

TODO:
- continue gathering groups feedback from users. evaluate how they interpret it alongside cohorts
- conduct internal user testing on usability

**Comment by paolodamico** [comment]
Very related to what @macobo said, I think we can start with which questions are we trying to answer that we can’t (like the one you suggested), and then see if cohorts is the answer and how. This will also help us prioritise as it’s unclear what stuff is more important, not only between cohort features but against cost of opportunity of other features. While I think cohorts improvements are important, I’m not convinced it’s the most important thing we could be working on. 

I suggest documenting these questions/problems in an RFC and then using that as a basis for prioritising improvements.
