### ISSUE TITLE
Improve plugin server reliability and management

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#7980]
WIP. An issue for me to keep track of various problems and to-dos regarding the reliability of the plugin server, as well as our ability to manage and debug it.

## Tasks

- [x] "Stateless plugins": #8112 
- [x] More useful context regarding plugin servers in system status
    - [x] https://github.com/PostHog/posthog/pull/7979   
- [ ] Make sure more than one plugin server can do work on self-hosted instances: https://github.com/PostHog/charts-clickhouse/pull/243
- [x] Healthcheck endpoint: https://github.com/PostHog/posthog/pull/7983
- [ ] Migrate `exportEvents` to a jobs-based mechanism (https://github.com/PostHog/posthog/issues/7755)
- [x] Improve observability/metrics
    - [x] #8116 
- [x] Debug "mysterious crashes"

to be continued...
