### ISSUE TITLE
[Epic] Deployment master plan

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#799]
We'd like it to be as easy as possible to deploy PostHog. We want to create specific instructions on how to deploy on a variety of platforms and providers.

- [ ] AWS
  - [x] ECS
  - [ ] EC2?
  - [x] Is there a one-click marketplace equivalent?
- [ ] Azure
- [x] Heroku
  - [ ] add-on [#837]
- [ ] GCP
- [ ] Fly.io
  - They've offered to do rev-share, but questionmarks around how to deploy database and redis server here
For these I think we should point to docker and docker-compose since those abstract away the complexities of the local package management and python version hastle
- [x] Ubuntu? (Could either be easily build from source or just docker-compose instructions)
- [x] Debian?
- [x] CentOS?

For each of these
- [ ] Add logo to frontpage with link
- [ ] Add instructions to /docs/deployment

One click deploys:
- [ ] Heroku
- [ ] DigitalOcean [#905]
- [ ] Linode

*(Feel free to just edit this description)*

**Comment by jamesefhawkins** [comment]
There is a one-click marketplace for AWS:
- [ ] https://docs.aws.amazon.com/marketplace/latest/userguide/product-submission.html

Likewise, getting listed in the following would also have a similar effect:

- [ ] https://bitnami.com/partners/isv-si
- [ ] https://marketplace.digitalocean.com/vendors

Maybe a separate issue, but it'd also be kind of interesting to see what we could do with plugins, by using them not just to integrate with our API key, but to create the account too. For example if we published something [like this](https://en-gb.wordpress.org/plugins/developers/), we could have it (i) set up PostHog snippet (ii) set up a PostHog account for you with some limited free usage (iii) have a field where you could input your own API key in case you want to self host

**Comment by fuziontech** [comment]
https://registry.terraform.io/ - would go a long way as well

**Comment by blarghmatey** [comment]
Linode also has a marketplace that they've released for one-click deployments https://www.linode.com/marketplace/

**Comment by jamesefhawkins** [comment]
A suggestion from a user on Heroku that fits well with what we're trying to do here:

"a zero configuration add-on in heroku would be amazing and would 100% meet my needs"

**Comment by jamesefhawkins** [comment]
Two more really good ideas from an investor:

- [ ] [Netlify](https://docs.netlify.com/partner-add-ons/get-started/#work-with-add-ons)
- [ ] [Vercel](https://vercel.com/integrations?category=analytics)

**Comment by fuziontech** [comment]
Dug into Vercel over the weekend and the way you build integrations is the provisioning pattern where you inject an interface onto their dashboard where a user can manage their PostHog integration.
https://vercel.com/integrations/posthog

Would be interesting, but I'd like to make sure that the value is there before we invest a ton of time into it. Would be nice to chat with Vercel to explore a partnership there.

I started building out a packer image for deploying to GCP and then took a break to look into applying to become a partner. Their docs really bummed me out:
https://cloud.google.com/marketplace/docs/partners#requirements
Specifically these two requirements.
- Your organization must have at least $1M in annual revenue.
- Your product must not have a dependency on Terraform.

I am going to punt on these to later and look into Heroku integration as an add-on and potentially using that as an early source of revenue.

**Comment by Twixes** [comment]
Closing due to direction change, feel free to reopen if relevant.
