### ISSUE TITLE
Experimentation Beta Release Checklist

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#8147]
In order to get Experimentation ready for beta release, there's a few things we need to do (code stuff on top, since that needs to happen before break-the-release)

- [x] Resolve trends significance issues
- [x] Improve recommended times by bringing back some sensitivity measure (MDE)
- [x] Explain its only for `posthog-js`
- [x] Polish frontend, get rid of outstanding bugs
- [x] Beta tag for Experimentation
- [x] Instrumentation - experiment created, saved, launched, filters, etc.
- [x] Enterprise/Scale feature licensing

And some things to make it easier for users to run experiments:
- [x] Experiment Implementation Guide & Gotchas: Use `onFeatureFlag`, as flags are loaded asynchronously.
- [x] User tutorial on how to run an experiment
- [x] Docs on how things work

cc: @liyiy @paolodamico @clarkus if I missed anything

----

> Improve recommended times by bringing back some sensitivity measure (MDE)

This appears to be a crucial requirement to me, as without this, the experience kindof remains terrible: with running times all over the place (even if they can be resolved quickly later on). Thoughts? Trying to do this might mean we don't get things done in time for the release, but the way I'm seeing things: first impressions for this feature are important, since it takes *a lot* of effort to run experiments well, and if we're wayy too off with our recommendations / significance testing, it doesn't inspire trust in the product. I'd rather release next month in that case 🤷‍♂️ .

**Comment by liyiy** [comment]
what is this referring to ` Resolve trends significance issues` and ` Enterprise/Scale feature licensing `?

Also suggestion to beta release this to just cloud users for now so we can fix bugs etc as an ongoing effort instead of trying to rush everything in the next 2 days

**Comment by neilkakkar** [comment]
Heya Li! For both trends and funnels, our significance calculations were pretty terrible and inconsistent. Fixing those.

Enterprise/Scale licensing is about making Experiments a paid feature!

**Comment by neilkakkar** [comment]
All done, docs will release soon, and we can release the FF then!
