### ISSUE TITLE
Taxonomy -> Event Management: Source of Truth Doc

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#8203]
This document will be used as the source of truth for ongoing work on Taxonomy and splits up work into discrete stages of work. `Event Management` is probably a better name for this work instead of `Taxonomy` so I'll use that moving forward. Any updates to the project will be tracked here.

@rcmarron @clarkus @paolodamico @mariusandra @marcushyett-ph 

**Problem: Users have no way of organizing events that come into PostHog. This can create noise that can distract users from what they really want to find.**

## Stage 1: Expose definitions

Mockups - https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=6727%3A44418

- [x] High fidelity mockups for definition cards and single definition read/write modes
- [ ] Create cohort/group/person property definitions or migrate into existing event/property definitions tables.
- [x] Allow adding descriptions and tags in actions. https://github.com/PostHog/posthog/pull/8272
- [x] Revamp definitions cards for hover actions across app (i.e., taxonomic filter, in-table properties)
- [x] Allow editing descriptions in contextual management of single definition (event, event property, actor property)
- [x] Events page -> Data Management page revamp
- [x] https://github.com/PostHog/posthog/issues/8144
- [ ] Expose events using property
- [ ] Fix property stats - https://github.com/PostHog/posthog/issues/7891

End goal: By the end of this stage, users should be able to see and edit definitions across the app. 

## Stage 2: Better definitions filtering in taxonomic filter

- Add `last_seen_at` and `created_at` fields to `EventProperty` model. https://github.com/PostHog/posthog/pull/8153
- Backfill `EventProperty` with historical event-property pairings.
- Figure out sort algorithm for https://github.com/PostHog/posthog/issues/8119
- Only show event properties that belong in that event. Do the same thing for actions

End goal: By the end of this stage, users should be able to find events and event properties in the taxonomic filter much quickly.

---

## Stage 3: Consolidate actions into events (needs discussion)

End goal: By the end of this stage, user should be able to create a definition for an action in the same flow as they would  for an event definition.

## Stage 4: Completeness/Event Verification (needs discussion)

End goal: By the end of this stage, user should be able to verify one or multiple definitions easily. Verified events should also reflect some UX change that helps users build the queries they want.

## Fit and Finish

- Dog fooding
- Bug squashing

## Potentially in scope. Open for discussion

- Typing properties (needs major discussion about value this actually brings)
- PII (I can see this becoming a big project in itself. Might be better off as its own smaller milestone.) https://github.com/PostHog/posthog/issues/7989
- Local vs. Global properties
- Optional and Required fields
- Stage 3
- Emails (opens can of worms like email settings)

**Comment by paolodamico** [comment]
- Is the intent to do all four stages in this sprint? It's a bit unclear what we want to accomplish from the Engineering side this sprint. I think we could summarize the most important points as such (which would then encompass most of the items you described above?):
    1. Surface taxonomy across the app (#8144)
    2. Expand taxonomy to actions, cohorts & user props. 
    3. Allow event verification.

**Comment by alexkim205** [comment]
Nope all the stages aren't meant to be for this sprint but this list is just to have a reference sheet for design, product, and engineering to so that we always know what to tackle next. 

@paolodamico I've shortened the details in the issue description to clarify what we want to accomplish here.

**Comment by rcmarron** [comment]
Moving a discussion from slack to here. 

Question: **Should person/group properties be kept separate from event properties?**

In our current designs, the data management page has a single tab for properties with the idea that a property definition is shared across events, persons, groups etc.

Pros of this design is that it's simpler and leads to fewer concepts for users to wrap their minds around.

Cons of this design is that person/group properties can be pretty distinct from event properties. A couple of notable distinctions outside of hanging off of different object types:
- Person/group properties can have the set_once concept
- The "last seen" concept isn't as interesting. It's more of a "number of users/groups with this set"
- If we merge them, they'd share a description/tags, so we would probably have to make it clear that this property is used on "50 events and the person person object" and that feels kind of clunky.
- Maybe not the best reason, but in the backend, they're different things, so it'd be a chunk of work to merge the concepts.

I'm in camp keep them separate, but curious if others have thoughts here

(cc @alexkim205 @clarkus @paolodamico @mariusandra)

**Comment by mariusandra** [comment]
We don't create a new property definition when a never before seen person property is ingested. Thus they're already separate due to this.

**Comment by clarkus** [comment]
> In our current designs, the data management page has a single tab for properties with the idea that a property definition is shared across events, persons, groups etc.

Just clarifying that it's like this because of how I understood the technical constraints, not any user-facing intent to simplify data management. 👍 

> Question: Should person/group properties be kept separate from event properties?

I also think it's worth asking about properties that exist for multiple event types, not just those for persons / groups. As an example, `version` is a custom property that is available for a pageview event and a person object. When I edit that property, which am I editing? We have some reserved properties, `country code` for example, that exist across types, too.

**Comment by timgl** [comment]
My biggest wish is to add the ability to remove events, event properties and person properties that are no longer used or are incorrect. It comes up quite a lot ([example](https://posthog.slack.com/archives/C02LR7352SG/p1644259068290169?thread_ts=1644250577.351259&cid=C02LR7352SG)). Can we add that to this project?

**Comment by alexkim205** [comment]
Yeah that definitely is under the scope of taxonomy. "Deprecating" events, event properties, and person properties app-wide might have a large blast radius that has to be thought out a bit more before tackling. Some open questions that we should answer before implementation.

1. Can "deprecated" events/properties be "reactivated"?
2. Are "deprecated" events blocklisted at ingestion or on exposing them in the app?
3. Does "deprecated" clash with the concept of "verification?" (see above). If so should they be consolidated?
4. What does it mean for a property to be "deprecated" if the other properties in that event are still "active"?

My 2c:

1. Yes. 
2. Answer to Q1 decides this. Ideally we continue ingesting everything and only block on exposing them in the app. We already functionally surface this with funnel exclusion filters, but in this case, this would be an app wide filter.
3. Not sure what the least confusing term for this process would be - "hidden", "deprecate", "incomplete"? Might be a problem UX can solve @clarkus. 
4. If we choose to do a soft deprecation (hide only at app-level not at ingestion), it would be easy to hide all references to a property in the app. It gets trickier with a hard deprecation (block at ingestion).

**Comment by clarkus** [comment]
To me, deprecation means "don't show me this in the product interface anymore". That means users with sufficient permissions could reactive an event in the future. I think verifying events is a bit of a social process, so I do think there is a case for deprecation and verification. As you see events come in, you're going to compare and verify the good and probably hide the junk events. If you make an error, you can always go back and change things around. It's going to take time to figure that out, and it might require multiple collaborators, so it makes sense to me to allow for each state. This would make it so any insight using a deprecated event could still function. The event just wouldn't show up in new creation workflows.
