### ISSUE TITLE
Dead Letter Queue Stats & Producer

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#8266]
# To-dos

- [x] Add basic metrics to system status: #8294 
- [x] Add a dedicated page with metrics
    - [x] #8347 
    - [x] #8447
- [ ] Add a management page to trigger DLQ ingestion
    - [ ] Filters
- [ ] ~~Auto ingestion retries from DLQ~~: Depends on out of order ingestion
- [x] Send to dead letter queue if Postgres is down: This was already the case

## Misc.

- [x] https://github.com/PostHog/posthog/pull/8345

# Dead letter queue superpowers

We have a dead letter queue, yay! It helps us not lose events when bad stuff happens.

However, we don't really have a lot of insight into what's going on inside it, nor do we have an established way to consume those events back.

Thus, I'm proposing:

1. Add dead letter queue metrics to system status (overall size, total events from today)
2. Add a dead letter queue management page

Regarding the management page, I'm thinking we would provide:

**Metrics**

More nuanced than system status. Have total size, event count by `error_location`, event count by `error`, event count per `day`.

**Trigger to ingest**

I'm thinking we can add a section to trigger an ingestion retry on events, with some filters available. Things like:

- Date filter: retry events from between dates X and Y
- Error filter: retry events with this error (e.g. `ingestEvent failed. Error: pgbouncer cannot connect to server` which is the cause that brought half of our current Cloud DLQ events there)
- Error location filter: retry events that failed in the plugin server vs. the Django server

I'm then thinking on a trigger we'd dispatch a task to Celery to pull events from CH and produce them to Kafka. We can also keep a model with a log so we can see each time this was triggered, by who, and when. This would also ensure we don't run multiple of these at once.

--------

Thoughts?

**Comment by guidoiaquinti** [comment]
Overall LGTM. Regarding the retry/ingestion: what about having a celery task enabled by default?

**Comment by yakkomajuri** [comment]
> Regarding the retry/ingestion: what about having a celery task enabled by default?

We could probably configure some sensible defaults with exponential backoff. Need to think about it more deeply though as e.g. during our Friday outage these would just continuously bounce (and add load we were trying to reduce).

**Comment by guidoiaquinti** [comment]
> > Regarding the retry/ingestion: what about having a celery task enabled by default?
> 
> We could probably configure some sensible defaults with exponential backoff. Need to think about it more deeply though as e.g. during our Friday outage these would just continuously bounce (and add load we were trying to reduce).

Sure, you can avoid that with an healthcheck + exponential backoff + jitter
