### ISSUE TITLE
Plan for rolling out persons/groups on events to individual Cloud teams

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9555]
A document outlining our plan for having specific teams on Cloud running the full persons/groups on events setup (both old and new events).

## Scaffolding

- [x] We must be ingesting events fully via JSON on Cloud (#9207)
- [x] #9510 needs to be live on Cloud
- [ ] We need to have a system in place for producing events with all the necessary data
    - [x] #9377 
    - [x] #9404  
    - [x] #9543 
- [x] #9182 
- [x] #9181
- [ ] Have a script that runs the necessary backfill for a given team based on #9186 

## Steps

1. Add the team to the plugin server env var `PERSONS_AND_GROUPS_INFO_TO_REDIS_TEAMS`
2. Add the team to the plugin server env var `CONVERSION_BUFFER_ENABLED_TEAMS`
3. Ensure events are coming in with the persons and groups data
4. Run the migration to backfill the teams events
5. Ensure all events were backfilled correctly
6. Run test queries using the new columns

## Things to watch out for

- Redis config in production (we should evict older keys if we're running out of space)
- Kafka buffer topic size
- ClickHouse `ALTER` for the backfill
- Ingestion time for non-buffer events

**Comment by tiina303** [comment]
> Redis config in production (we should evict older keys if we're running out of space)

Looked into Redis configs via 
```
(redis pod shell)$ redis-cli
redis-cli> INFO
```
localhost: `maxmemory_policy:noeviction`
playground i.e. self-hosted default: `maxmemory_policy:noeviction`

i.e. this is something we need to change. I proposed earlier that we should use `volatile-lru` [in a comment here](https://github.com/PostHog/posthog/issues/9179#issuecomment-1094289953)

**Comment by yakkomajuri** [comment]
We should have that on Cloud already:

> By default, Amazon ElastiCache for Redis sets the volatile-lru eviction policy for your Redis cluster. When this policy is selected, the least recently used (LRU) keys that have an expiration (TTL) value set are evicted. Other eviction policies are available and can be applied in the configurable maxmemory-policy parameter.

[_[source]_
](https://docs.aws.amazon.com/whitepapers/latest/database-caching-strategies-using-redis/evictions.html)
So makes sense to set self-hosted to it.

I'd go as far as suggesting `allkeys-lru` but happy to move in baby steps here.

**Comment by tiina303** [comment]
> I'd go as far as suggesting allkeys-lru but happy to move in baby steps here.

I'd say we should set expire on keys if they should be able to expire (can be super long), seems safer, I'm not sure what keys we currently store in Redis and what assumptions we're making about them being there.

**Comment by yakkomajuri** [comment]
We use Redis the standard way - it's a cache and we should build systems in a way that they are fine if it disappears

**Comment by tiina303** [comment]
>  it's a cache and we should build systems in a way that they are fine if it disappears 

I agree, but it's worth checking the current usage before we change over though.

Further reading ([here](https://redis.io/docs/manual/eviction/)):
>It is also worth noting that setting an expire value to a key costs memory, so using a policy like allkeys-lru is more memory efficient since there is no need for an expire configuration for the key to be evicted under memory pressure.

Based on this I propose we drop the expiry and make us use `allkeys-lru`.

**Comment by tiina303** [comment]
Based on [this](https://it-qa.com/what-to-do-when-redis-runs-out-of-memory/) (though surely there's a better resource to confirm it)
> If you turn maxmemory off, Redis will start using virtual memory (i.e. swap), and performance will drop tremendously.

So we should set `maxmemory` too, when key-eviction starts happening.

**Comment by tiina303** [comment]
For verification we should check that we're done by querying `person_id != ‘000…’` for the team
